### PR TITLE
Add a contribs/gmf directory

### PR DESCRIPTION
**Pull request by elemoine**
I'm opening this PR for discussion.

The PR adds a `contribs/gmf` directory to be used for GeoMapFish-related components and examples. In this way we make it clear to external users that ngeo is not tied to GeoMapFish.

The infrastructure is not yet complete, but I'd like to know whether people agree with this way of structuring things before continuing on.

### CODE REVIEW

**Comment by fgravin** [comment]
I share the same ideas.
+1

**Comment by tonio** [comment]
It’s much clear like this. :+1:

**Comment by fredj** [comment]
+1

**Comment by elemoine** [comment]
Things to do:

* [ ] Check GMF examples with PhantomJS
* [ ] Add GMF examples to GH pages

**Comment by asaunier** [comment]
Makes sense indeed. But shouldn't the README advertise these new contribs examples as it does for the standard examples?

**Comment by elemoine** [comment]
> Makes sense indeed. But shouldn't the README advertise these new contribs examples as it does for the standard examples?

Yes, indeed.

**Comment by elemoine** [comment]
> Makes sense indeed. But shouldn't the README advertise these new contribs examples as it does for the standard examples?

I decided not to do that at this point, given that we currently just have the gmf simple example. We can advertise the gmf examples when we have more examples to show.

That being said the gmf examples will be available at https://camptocamp.github.io/ngeo/master/gmf.

**Comment by elemoine** [comment]
I am done. Please review.

**Comment by elemoine** [comment]
I changed paths, and the gmf examples should now be available at https://camptocamp.github.io/ngeo/master/contribs/gmf (when this is merged).

**Comment by elemoine** [comment]
I am done again. I'll merge this, unless there are other comments.

**Comment by asaunier** [comment]
For me it's OK.

**Pull request merged**
