### PR TITLE
Move ngeo global enums

### PR DESCRIPTION
**Pull request by ger-benjamin**
For https://jira.camptocamp.com/browse/GSGMF-223
Also move ngeo.Attribute into format, according to https://jira.camptocamp.com/browse/GSGMF-172 (last file of the list)

### CODE REVIEW

**Comment by pfirpfel** [comment]
Should we re-introduce the enums I removed [here](https://github.com/camptocamp/ngeo/pull/3373) (#3373, commit: https://github.com/camptocamp/ngeo/pull/3373/commits/e7159c068413d49332aa13bbc5294c825d9bf040 )?

**Comment by ger-benjamin** [comment]
@gberaudo according to what Pfirpfel as said, should I remove some enums ?

**Comment by gberaudo** [comment]
Post merge comment: +1 for merging as-is since the enum porting work is done.
Looking at the code, I think all enums except conditions and featureProperties should have been plain strings. That is a detail that may be addressed at the end of the project.

**Comment by ger-benjamin** [comment]
> all enums except conditions and featureProperties should have been plain strings
I agree

**Pull request merged**
