### PR TITLE
Add ngdoc and ngname tags

### PR DESCRIPTION
**Pull request by sbrunner**
Display angular types and names

alternative of #400

### CODE REVIEW

**Comment by sbrunner** [comment]
Result: http://camptocamp.github.io/ngeo/Angular-JSDoc2/apidoc/

**Comment by asaunier** [comment]
Same question than for #400 
I prefer this white background layout.

**Comment by sbrunner** [comment]
And on this one the (more) links will works +1 for this one

**Comment by ger-benjamin** [comment]
I prefer this layout too.

**Comment by sbrunner** [comment]
fix #345

**Comment by fredj** [comment]
+1

**Comment by sbrunner** [comment]
The most important difference of those pull requests is not the layout but the generated doc.

In the #400 we are based on the angular-template witch is made for angular object but don't support wheel standard object... see: http://camptocamp.github.io/ngeo/Angular-JSDoc/apidoc/ngeo.interaction.Measure.html vs http://camptocamp.github.io/ngeo/Angular-JSDoc2/apidoc/ngeo.interaction.Measure.html

And in #402 the link generation is much better :-)

**Pull request merged**
