### PR TITLE
Fixing some permalink issues

### PR DESCRIPTION
**Pull request by olivierSemet**
For now:

- The permalink is not fully generated during the initialization phase and therefore does not reflect the state from the localStorage one. 

 - - [ ] This should be fixed now.

- The permalink initialization does not take care of mixed groups inside a mixed group 

 - - [ ] This should be fixed now.

Demo: https://oliviersemet.github.io/ngeo/permalink-enhancement/examples/contribs/gmf/apps/desktop_alt/

**Empty you localStorage and reload before testing the app** 

@pgiraud @fredj @sbrunner Could you review and check ?

### CODE REVIEW

**Comment by sbrunner** [comment]
The generated permalink is wrong:
when I enable the layer `osm_open` I see:
`tree_enable_osm_open=true`
but it should be (see: https://github.com/camptocamp/c2cgeoportal/issues/1657):
`tree_group_layers_osm_function=osm_open,...`
This should work at least on reading, If it's better to change it you should add the gorup name =>
`tree_enable_osm_function_osm_open=true`...

**Comment by sbrunner** [comment]
I just see that's was wrong before ...

**Comment by olivierSemet** [comment]
Not I sure I understood:

> tree_enable_<layer_name>. Is the layer enabled for external layers (present only if it's not the default)

Is the localStorage/url queryParameterkey key used for external layers like osm_open (it's in mixed group). So regarding the spec [#1657](https://github.com/camptocamp/c2cgeoportal/issues/1657) it seems to be good.

> tree_group_layers_<group_name>: List of visible layers (present only if it's not the default)


Is the localStorage/url queryParameterkey key used for internal layers like those containing in "groups" for example

**Comment by olivierSemet** [comment]
The link for the demo was not the good one. It's good now

**Comment by sbrunner** [comment]
Sorry, I miss that's was a mixed group :-)

**Comment by olivierSemet** [comment]
We can close this PR, I'll produce a global one. Thanks

**Pull request closed without merging**
