### PR TITLE
Don't include gmf.ObjectEditingManager in permalink

### LINKED ISSUE #2844: Non working gmf example
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/elevation.html
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/drawfeature.html

Error is:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.6.6/$injector/unpr?p0=gmfLayersUrlProvider%20%3C-%20gmfLayersUrl%20%3C-%20gmfEditFeature%20%3C-%20gmfObjectEditingManager%20%3C-%20gmfPermalink
```

### PR DESCRIPTION
**Pull request by fredj**
fixes #2844 

was added in #2832

### CODE REVIEW

**Comment by sbrunner** [comment]
Or we can evantually add `gmf.ObjectEditingManager` (the js :-) ) in the js list, see also: #2834, #2832

**Comment by gberaudo** [comment]
@sbrunner, are you going to add a Docker build in ngeo?

**Comment by sbrunner** [comment]
Actually I didn't plan that but we effectively can do that :-)

**Comment by fredj** [comment]
the mobile app is also broken because of that #2859

**Comment by pfirpfel** [comment]
Fixed with #3025

**Pull request closed without merging**
