### PR TITLE
Ngdoc - name default template

### PR DESCRIPTION
**Pull request by sbrunner**
Add the @ngdoc tag
Set the @name to the <package>.<angular name>
Use the standard template

### CODE REVIEW

**Comment by sbrunner** [comment]
Result: http://camptocamp.github.io/ngeo/Angular-JSDoc/apidoc/

**Comment by asaunier** [comment]
Nice!
Is "Angular-JSDoc" really needed in the URL? Can't we simply use http://camptocamp.github.io/ngeo/apidoc/ ?

**Comment by sbrunner** [comment]
Yes, it's the branch name, finally it will me in:  http://camptocamp.github.io/ngeo/master/apidoc/
One documentation per major release is required :-)

**Comment by asaunier** [comment]
OK, this makes sense.

**Pull request closed without merging**
