### PR TITLE
Min and max time can be null

### PR DESCRIPTION
**Pull request by sbrunner**
Fix GEO-4084

### CODE REVIEW

**Comment by asaunier** [comment]
@sbrunner What's the connection between a date selector in italian and null min/max times?

**Comment by sbrunner** [comment]
null min/max times throws an error that skip the language switch ...

**Comment by asaunier** [comment]
Thanks! Good to know for reviewers :)

**Review by ger-benjamin — APPROVED** [review]
That's what we should avoid throwing error, at least in AngularJS.
But should we not do a `console.error('Missing minTime')` ? Otherwise, we don't know there is an error in our configuration

**Comment by sbrunner** [comment]
But it's not an error, the field can be initialized with no value...

**Pull request merged**
