### PR TITLE
Assign a uid to tree and child nodes

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by elemoine** [comment]
Looks good to me.

But perhaps this needs explanations here in the PR. The user of the `ngeoLayertree` and `ngeoLayertreenode` directives can use the `uid`s in his partials, if using `id`'s in HTML elements is required (because of Bootstrap for example).

**Comment by asaunier** [comment]
> The user of the ngeoLayertree and ngeoLayertreenode directives can use the uids in his partials, if using id's in HTML elements is required (because of Bootstrap for example).

Would you have an example? In Lux maybe?

**Comment by pgiraud** [comment]
Yes, see https://github.com/Geoportail-Luxembourg/geoportailv3/commit/55c07d3bd99bc690418c726f8534208fe39ff2c0

**Comment by elemoine** [comment]
> Would you have an example? In Lux maybe?

Adding ids to HTML elements in directive partials is not a good practice, because directives may be used multiple times in a page. But, unfortunately, it looks like some Bootstrap components require adding ids to elements. See the [Bootstrap collapse component](http://getbootstrap.com/javascript/#collapse) for example.

**Pull request merged**
