### PR TITLE
Adding theme selector + layer tree in desktop app

### PR DESCRIPTION
**Pull request by pgiraud**
https://pgiraud.github.io/ngeo/desktop_theme/examples/contribs/gmf/apps/desktop/index.html

It still needs some styling.

[https://github.com/camptocamp/c2cgeoportal/issues/1839]

### CODE REVIEW

**Comment by sbrunner** [comment]
Witch CORS issue?
https://pgiraud.github.io/ngeo/desktop_theme/examples/contribs/gmf/apps/desktop/index.html/theme/main works for me ...

**Comment by pgiraud** [comment]
Do you see the map and is the theme selector filled?

**Comment by sbrunner** [comment]
Yes booth :-)

**Comment by pgiraud** [comment]
OK, I had to force the reload of the page in my browser. (clear cache?).
Description updated.

**Comment by sbrunner** [comment]
;-)

**Comment by sbrunner** [comment]
> It still needs some styling.

does it steal true?

**Comment by pgiraud** [comment]
It's still true but this can be addressed later. It's not blocking.
Here's what I think is not pretty enough:
 - theme selector dropdown content : thumbnails and text could be arranged differently,
 - theme selector button : it would be better to have the text aligned left and the caret aligned right,
 - tree : it doesn't look like how it was designed.

**Comment by sbrunner** [comment]
OK, then that's looks good for me :-)

**Comment by sbrunner** [comment]
Added to the main issue https://github.com/camptocamp/c2cgeoportal/issues/1839

**Pull request merged**
