### PR TITLE
Use externe file for gmf User

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix: https://github.com/camptocamp/c2cgeoportal/issues/2216

Example:  http://ger-benjamin.github.io/ngeo/user_externs/examples/contribs/gmf/apps/desktop
@sbrunner I currently target the branch "master" but this PR aims a 2.0 bug. It is correct or I should push it on the 2.0 ?

### CODE REVIEW

**Comment by fredj** [comment]
ping @sbrunner

**Comment by sbrunner** [comment]
The code don't speak to me, The demo looks good :-)

**Comment by fredj** [comment]
The code looks good to me; do we have to backport it to the 2.0 ?

**Comment by sbrunner** [comment]
+1 it should be on 2.0 :-)

**Comment by fredj** [comment]
> +1 it should be on 2.0 :-)

See #1313

**Pull request merged**
