### PR TITLE
Fix resize map

### PR DESCRIPTION
**Pull request by llienher**

### CODE REVIEW

**Review by vuilleumierc — APPROVED** [review]

**Comment by sbrunner** [comment]
`flex-shrink` should be set to `0` on `#gmf-app-panel-separator-container`...

**Comment by sbrunner** [comment]
The print mask display hide is delayed on mouse move ...

**Comment by llienher** [comment]
> The print mask display hide is delayed on mouse move ...

@sbrunner Not related to this PR, seems to be the same on master now ...

**Comment by sbrunner** [comment]
Yes, it can be added to the issue or in a new issue :-)

**Comment by llienher** [comment]
@sbrunner I will not fix print stuff in this PR/issue, so we make a new one. :-)

**Review by sbrunner — APPROVED** [review]

**Pull request merged**
