### PR TITLE
Travis cleanup

### PR DESCRIPTION
**Pull request by fredj**
Activate caching in travis, see http://docs.travis-ci.com/user/caching/

### CODE REVIEW

**Comment by elemoine** [comment]
Should this be merged

**Comment by fredj** [comment]
Ready to be merged

**Comment by elemoine** [comment]
Cool. I just wonder if we could remove 

```
="
addons:
  apt:
    packages:
    - python-virtualenv
```
by replacing 

```
language: ruby
```

by

```
language: python
```

I'll try.

**Comment by elemoine** [comment]
Please merge when Travis is happy.

**Pull request merged**
