### PR TITLE
Add ObjectEditing Edit application (skeleton)

### PR DESCRIPTION
**Pull request by adube**
This PR introduces a new application: the 'Edit' page of the ObjectEditing project.

## Todo

 * [x] build JavaScript
 * [x] build CSS
 * [x] review

### CODE REVIEW

**Comment by adube** [comment]
I need instructions how to build the JS and CSS, please.

**Comment by sbrunner** [comment]
You should just add the new applications here:
https://github.com/camptocamp/ngeo/blob/master/Makefile#L21 :-)

**Comment by adube** [comment]
Wow, that was simple!  Thanks for pointing that out!  I made the change and wait to see if that does everything I need.

**Comment by adube** [comment]
Okay, ready for review.

One detail, though: I used to be able to do `make check-examples` in order to create live examples, but I no longer can as it always returns errors, such as:

```
EXIT 0
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/32/42.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/11/16.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/12/17.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/13/17.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/63/82.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/63/83.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/30/41.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/31/42.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/11/17.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/0/1/0.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/13/16.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/64/83.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/7/9.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/7/8.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/14/16.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/30/42.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/64/82.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/2/1/3.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/33/41.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/6/9.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/62/82.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/2/2/3.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/0/1/1.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/5/9.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/1/1/0.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/1/0/1.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/65/83.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/0/0/0.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/33/42.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/31/41.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/1/0/0.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/5/32/41.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/62/83.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/2/2/2.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/6/8.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/1/1/1.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/14/17.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/2/1/2.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/6/65/82.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/4/12/16.png
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.1/wsgi/mapserv_proxy?ogcserver=Main+PNG&cache_version=7160501df3dd4e8bbfa37df48f8a917a&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&LAYER=bus_stop&SCALE=71428.42857142855
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.1/wsgi/mapserv_proxy?ogcserver=Main+PNG&cache_version=7160501df3dd4e8bbfa37df48f8a917a&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&LAYER=parking&SCALE=71428.42857142855
Resource error: 5, https://geomapfish-demo.camptocamp.net/2.0/tiles/1.0.0/map/default/swissgrid_005/3/5/8.png
URL changed: about:blank
```

Does that prevent the build to work?

**Comment by sbrunner** [comment]
When we do a check of an example we wait for an arbitrary time (https://github.com/camptocamp/ngeo/blob/master/buildtools/check-example.js#L49) and all the pending request on the timeout will log something like this, but the build will not failed...

**Comment by adube** [comment]
Understood, thanks.

**Pull request merged**
