### PR TITLE
Gmf add loading div onload

### PR DESCRIPTION
**Pull request by julsbreakdown**
see https://jira.camptocamp.com/browse/GSGMF-606

This PR brings a loading mask on both the mobile & desktop application.

### CODE REVIEW

**Comment by julsbreakdown** [comment]
will look like this
image

**Comment by julsbreakdown** [comment]
and mobile view
image

**Comment by sbrunner** [comment]
Your screen shot are completely different from the mockups...

**Comment by julsbreakdown** [comment]
I do not have access to the mockups...

**Comment by julsbreakdown** [comment]
Can you share them here

**Comment by julsbreakdown** [comment]
@sbrunner this is ready

**Pull request merged**
