### PR TITLE
Fix themes.json - mixed should have a boolean value

### PR DESCRIPTION
**Pull request by adube**
This PR fixes the `"mixed"` values inside the themes.json file that were strings to boolean.

The official theme service returns a boolean for `"mixed"`.

### CODE REVIEW

**Comment by adube** [comment]
@fgravin Please, review.

**Comment by fredj** [comment]
LGTM

**Comment by fredj** [comment]
there are other "true" and "false" in this file (`wfsSupport`, `isChecked`, ...)

**Comment by adube** [comment]
Yes, but not all of them are correctly declared in the `gmf-themes.js` extern file, plus they are used as string when compared, i.e. `if (value == 'true')`.  I wouldn't touch them as part of this fix, as it could become much bigger of an issue.

I agree that this needs to be consistent, but this should be part of a separate task where both the server and client should be fixed.  Do you agree ?

**Comment by fredj** [comment]
Thanks @adube

**Pull request merged**
