### PR TITLE
Clean the CSS (add --clean-css=--s0 lessc argument)

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by gberaudo** [comment]
What about generating a sourcemap with `--source-map` or `--source-map-inline-sources` option?
https://github.com/jakubpawlowicz/clean-css

**Comment by sbrunner** [comment]
+1 for the second (for me the first one will probably not working)

**Comment by gberaudo** [comment]
Thanks, +1.

**Comment by sbrunner** [comment]
Merging without source-map (I don't succeed to make it working :-( )

**Comment by gberaudo** [comment]
Thanks @sbrunner for taking the time to try source maps and for the feedback.

**Pull request merged**
