### PR TITLE
Print enhancements

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix: #1108 
Demo: https://ger-benjamin.github.io/ngeo/print_enhancements/examples/contribs/gmf/apps/desktop

(@fredj Finally, I've put the css in the desktop because this rule on textareas is usefull for all tools)

### CODE REVIEW

**Comment by sbrunner** [comment]
The third point isn't fixed ...

Also that's looks good :-)

**Comment by ger-benjamin** [comment]
The third point must be fixed now. Example updated.

**Comment by sbrunner** [comment]
Excellent, thanks

**Comment by fredj** [comment]
thanks, please merge when travis is green

**Pull request merged**
