### PR TITLE
Query WMTS background layers

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/camptocamp/ngeo/issues/1238

Querying WMTS overlays was already supported, I only added a test for it.

### CODE REVIEW

**Comment by tsauerwein** [comment]
@sbrunner I would need this PR and https://github.com/camptocamp/ngeo/pull/1288 for my work on https://github.com/camptocamp/c2cgeoportal/issues/1771. What is your workflow to move these commits from 2.0 to master?

**Comment by tsauerwein** [comment]
A review would be appreciated.

**Comment by fredj** [comment]
> A review would be appreciated.

LGTM.

> What is your workflow to move these commits from 2.0 to master?

@sbrunner do you want to rebase 2.0 into master ? #1288 also needs to be ported to master

**Comment by fredj** [comment]
Please merge

**Comment by tsauerwein** [comment]
Thanks for the review!

**Pull request merged**
