### PR TITLE
WIP Lidarprofile 23

### PR DESCRIPTION
**Pull request by ger-benjamin**
This PR superseeds #3842, that superseeds original #3464. It convert lidarprofile to ngeo 2.3 (and is based with your last fixes @kalbermattenm , I've merged them into one commit)

WIP: The example works fine, but I can't test the app now, because gmf apps doens't work for now in ngeo.

### CODE REVIEW

**Comment by ger-benjamin** [comment]
Works fine now on desktop apps except for two things:
- @sbrunner Where should I define this value in the new architecture ?: https://github.com/monodo/ngeo/blob/4a45c36dada9576733f4e37cd43abf3676dbd0e5/contribs/gmf/apps/desktop_alt/index.html#L443 
- @sbrunner, @kalbermattenm The lidarprofile wants coordinates in EPSG2056, our map in the demo app is in EPSG21781. Why should I do ?

**Comment by sbrunner** [comment]
What about changing the projection in the desktop alt?

**Comment by kalbermattenm** [comment]
We (SITN) cannot, for sure, provide data in EPSG:21781...

> @sbrunner Where should I define this value in the new architecture ?

What about creating a fake webservice, serving always the same points, which would be a bit odd, but which would removing a dependency from your webservice... (we could even add some doc about that in the example)

**Comment by ger-benjamin** [comment]
> What about changing the projection in the desktop alt ?

As we have discussed, that's not so simple, because all widget that use the raster service (for elevation) will not work anymore, there is also also work with the background, a little bit for the search.
That's not impossible but that take a little bit time.

> Can't we re-projecte coordinates from the map to the lidar profile ?

That not so simple because we need to reproject the line AND the "mouseover" that display the information popup...

> What about creating a fake webservice ?

It's a possibility.

---

IMO, we should revert changes in the desktop_alt. So we will not have the Lidar Profile for now in our application desktop. We know that it works, you can see the revert commit to implement it into your application if you need it.
And if you want a demo, the example still works (contribs/gmf/example/lidarprofile).
And later, we re-add the Lidar profile in the desktop_alt.

**Comment by ger-benjamin** [comment]
@sbrunner @kalbermattenm Is this idea ok for you ? (I hope merging this afternoon)

**Comment by kalbermattenm** [comment]
+1, effectively, it looks like the easy way to resolve this problem.

**Comment by ger-benjamin** [comment]
Done, I've made a specific commit that add, and another that revert what we need to add in the application files to have the Lidar profile (see the two lasts commits).

I'll merge :tada:

**Pull request merged**
