### PR TITLE
[WIP] Add Theme Selector directive for GMF

### PR DESCRIPTION
**Pull request by adube**
Replaces #478.

Still in progress.  I just want to see the Travis report.  Please, wait for further details before reviewing.

### CODE REVIEW

**Comment by adube** [comment]
@fgravin:

 * template updated
 * filter option (function) now possible
 * added in mobile app

But in the mobile app it currently does nothing.  Please, help me understand how to make it actually do anything.

**Comment by adube** [comment]
One more important point.  There are themes that have the same name: "Enseignement".  This may result in making the selector not working properly.  Are they supposed to be unique ?  Please, let me know.

**Comment by fgravin** [comment]
> But in the mobile app it currently does nothing

It will update the layer tree, but the layertree is not yet in the modible application.
You must have a reference to the tree in the main controller, and this reference is updated when you select a theme.

Cf
```js
'currentTheme': '=gmfThemeselectorCurrenttheme'
```
and 

```html
 gmf-themeselector-currenttheme="ctrl.theme"
```

Main controller `theme` property will be the source of the layertree.
You may need to declare it in the main controller.

**Comment by fgravin** [comment]
> This may result in making the selector not working properly. Are they supposed to be unique ? Please, let me know

id should be unique, name i don't know.
Is it an error in the theme example ? @sbrunner 
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/data/themes.json#L479

**Comment by adube** [comment]
>id should be unique, name i don't know.
Is it an error in the theme example ? @sbrunner 
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/data/themes.json#L479

FYI, the name is used in the url.  If we switch to the id, it would work.  Otherwise, the name would need to be unique too.

**Comment by sbrunner** [comment]
No the id isn't unique but to element with the same id should be the same.

This is because in the database we have a "graph" and the theme webservice return a graph.

theme

**Comment by adube** [comment]
@sbrunner What's the solution, then ?

**Comment by sbrunner** [comment]
... I probably miss something... what's the issue?

**Comment by adube** [comment]
@sbrunner We use the name of the theme for selection purpose, and it's also added in the url.  If themes share the same name, then it causes the issue of both being selected when one is.

**Comment by sbrunner** [comment]
@adube can you call me on hangout ?

**Comment by fgravin** [comment]
merge all your commits in one before we merge your PR

**Comment by adube** [comment]
@fgravin Okay, this is ready for review.

Please, note that I did not use the theme service `find*` methods as I needed to find in the inner themes with the potential filter applied (if any).

**Comment by adube** [comment]
@sbrunner FYI, we're going to ignore the issue of the names that are not currently unique.

**Comment by fgravin** [comment]
Looks good.
Can I merge ?

**Comment by sbrunner** [comment]
Looks good to me to :-)

**Comment by sbrunner** [comment]
We potentially already have the issue with cgxp :-)

**Comment by adube** [comment]
>We potentially already have the issue with cgxp :-)

What do you mean ?

**Pull request merged**
