### PR TITLE
Some fix for js to ts

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by llienher** [comment]
I tested on the branch and have an issue with the notification.js file when doing the conversion:
```

 ERR src/message/Notification.js Transformation error (Cannot read property 'property' of undefined)
TypeError: Cannot read property 'property' of undefined
    at addTypes (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:87:56)
    at addTypes (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:119:14)
    at addTypes (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:74:12)
    at addTypes (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:74:12)
    at NodePath.<anonymous> (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:727:9)
    at /home/llienher/www/ngeo/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/home/llienher/www/ngeo/node_modules/jscodeshift/src/Collection.js:74:18)
    at transformer (/home/llienher/www/ngeo/buildtools/codeshift-js2ts.js:726:8)
All done. 

```

Is it related to something to manually change before or a new thing to fix here ?

**Comment by llienher** [comment]
By the way, the Service.js or Message.js files are converted correctly now. :-)

**Comment by sbrunner** [comment]
@llienher new version :-) can you convert the Service.js or Message.js again?

**Review by llienher — APPROVED** [review]
Works well.

I'm still not convinced how the enums are converted but I need to see how it works in practice. :-)

**Comment by llienher** [comment]
What we get from enums in the script:
```
export type MessageType = string;
export namespace MessageType {
    const ERROR: string;
    const INFORMATION: string;
    const SUCCESS: string;
    const WARNING: string;
}
```

What works in my code:
```
export enum MessageType {
  ERROR = 'error',
  INFORMATION = 'information',
  SUCCESS = 'success',
  WARNING = 'warning',
}
```

**Comment by sbrunner** [comment]
Will be in another pull request

**Pull request merged**
