### PR TITLE
Add methods to get corner of print mask

### PR DESCRIPTION
**Pull request by Jenselme**

### CODE REVIEW

**Comment by elemoine** [comment]
@Jenselme your branch includes a merge commit from master. You certainly want to remove it in order to get this PR reviewed. Thanks.

**Comment by Jenselme** [comment]
PR rebased, no more merge commit.

**Comment by ger-benjamin** [comment]
@pgiraud (you are the assignee) What is this PR..? Can we still rebase it ? Should we transform it into an issue ? or just trash it ?

**Comment by pgiraud** [comment]
I'd prefer we don't trash it. The code looks good and we may need this ourselves.
@Jenselme Is it something that you still use in your projects? If so, can you please rebase (once again) your branch on top of master? Thanks.

**Comment by Jenselme** [comment]
@pgiraud PR updated.

**Comment by pgiraud** [comment]
LGTM. Thank you. Merging.

**Pull request merged**
