### PR TITLE
Be able to correctly translate in french

### PR DESCRIPTION
**Pull request by sbrunner**
=> `Vous utilisez l'application mobile. Allez sur l'` + `application standard`

### CODE REVIEW

**Comment by gberaudo** [comment]
@sbrunner, see https://rocketeer.be/blog/2016/06/translate-params/.

**Comment by sbrunner** [comment]
=> ```html
<span translate 
  translate-params-url="http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/?no_redirect">You're using the mobile application. Check out the <a href="{{url}}">standard application</a>.</span>
```
?

**Comment by gberaudo** [comment]
@sbrunner, I think the URL should be quoted like this:
```html
  translate-params-url="'http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/?no_redirect'"
```

**Comment by sbrunner** [comment]
To be rested but the URL should already be quoted in `<a href="{{url}}">`...

**Comment by gberaudo** [comment]
No, I mean you need to quote the URL so that it is evalutated correctly by angular. Otherwise I guess it will consider your URL to be a variable.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Pull request merged**
