### PR TITLE
Add tooltip to search color picker

### LINKED ISSUE #1420: Add tooltip to the color chooser button and popover
See 665b68e

The tooltip content is not translated; `{{'Change the color of the search result'|translate}}` is displayed instead.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #1420.
`data-original-title` is to be used instead of `data-title`.

### CODE REVIEW

**Comment by pgiraud** [comment]
Actually, I think that the header in the popover is enough. There's no real need for a tooltip for this tool.
Opinions?

**Comment by fredj** [comment]
I also think that the popover header is enough

**Comment by pgiraud** [comment]
Unfortunately the tooltip header doesn't show up in built mode. I'll investigate.

**Comment by pgiraud** [comment]
For an unknown reason the text I put in the tooltip is also used as a title for the popover. I changed the pull request so that no tooltip appears but the title in the popover is kept.
https://pgiraud.github.io/ngeo/search_color_tooltip/examples/contribs/gmf/apps/desktop_alt

**Comment by fredj** [comment]
+1, thanks

**Pull request merged**
