### PR TITLE
Displaying loader when source is not available for a layer

### LINKED ISSUE #1057: "Source not available" displayed temporarily
In the desktop app, a "Source not available" appears furtively in layertree for the last two layers when loading the cadastre theme.

### LINKED ISSUE #1114: Don't put string in the less files
It's not possible to localized them
Found error:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/less/layertree.less#L156

### PR DESCRIPTION
**Pull request by olivierSemet**
closes #1114 
closes #1057 

demo:
- desktop app: https://oliviersemet.github.io/ngeo/source-not-available-wmts-layer/examples/contribs/gmf/apps/desktop/index.html

- mobile app: https://oliviersemet.github.io/ngeo/source-not-available-wmts-layer/examples/contribs/gmf/apps/mobile/index.html

@fredj @pgiraud

### CODE REVIEW

**Comment by pgiraud** [comment]
With this pull request, the "check" icon reappears. This is probably not the expected behavior.
Also in some cases there is a loader displayed on leaves in a group but no loader displaying at the group level. This is difficult to understand.
screenshot from 2016-06-13 13 29 59

**Comment by pgiraud** [comment]
@ybolognini This needs some discussion.

**Comment by ger-benjamin** [comment]
(I should review this PR) Where are we with this PR ? @pgiraud ?

**Comment by pgiraud** [comment]
Unfortunately, we haven't had any discussion with @ybolognini on this topic yet.

**Comment by pgiraud** [comment]
Addressed in #1487.

**Pull request closed without merging**
