### PR TITLE
Group the 'actions' results

### PR DESCRIPTION
**Pull request by fredj**
Group the search results by actions: "add_theme", "add_group" and "add_layer"

### CODE REVIEW

**Comment by fredj** [comment]
And it allows to ignore actions by removing the name from the `gmfSearchGroups`.
Example: only handle `add_theme`actions:
```js
module.constant('gmfSearchGroups', ['osm','district', 'add_theme']);
```

**Comment by fredj** [comment]
@sbrunner : updated

**Comment by sbrunner** [comment]
Looks good for me :-)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
