### PR TITLE
Fix the clean of gh-pages

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by ger-benjamin — APPROVED** [review]
What's the issue ? Can't we clean the branch ?
(Well, then, amending the last commit each time is not a problem for this branch)

**Comment by sbrunner** [comment]
> What's the issue ? 

It seems what when we push the content to the gh pages branch we reset to the first commit of the branch then we lost all the delete...

**Comment by sbrunner** [comment]
> Can't we clean the branch ?

I don't understand this question ...

**Comment by ger-benjamin** [comment]
> Can't we clean the branch ?
> I don't understand this question ...

Forget that, it doesn't make sense now that you explained me the issue

**Pull request merged**
