### PR TITLE
Work-around for download on Safari

### PR DESCRIPTION
**Pull request by tsauerwein**
There are several issues with the file download on Safari, see https://github.com/eligrey/FileSaver.js/issues/12. The latest Safari Tech Preview fixes these issues, but as long as no official release is available, it would be good to have a work-around.

The first commit addresses the problem that Safari is not able to start a download for files with a mime-type other than `text/plain`. So, when using Safari, the mime-type is set to `text/plain` (instead of the mime-type for csv/kml/gpx). This will open the file in a new tab and the user can download with `File -> Save as`. Not optimal, but as least the user can get the data.

The second commit deals with the problem that on Safari a download can only be started within 1000ms in the event handler of a *trusted event* (an event generated by a user action, like clicking the export button). Currently, a request is made to get the profile as CSV and then when the request succeeds, the download is started. But this doesn't work for Safari, the file would be shown in the same tab.
Instead the CSV file is generated on the client-side with the already available data.

Closes https://github.com/camptocamp/ngeo/issues/2083

### CODE REVIEW

**Comment by sbrunner** [comment]
https://docs.angularjs.org/error/$injector/unpr?p0=ngeoCsvDownloadProvider%20%3C-%20ngeoCsvDownload%20%3C-%20GmfProfileController in the profile example (on Travis) :-(

**Comment by tsauerwein** [comment]
> https://docs.angularjs.org/error/$injector/unpr?p0=ngeoCsvDownloadProvider%20%3C-%20ngeoCsvDownload%20%3C-%20GmfProfileController in the profile example (on Travis) :-(

Thanks, fixed.

**Comment by fredj** [comment]
LGTM, @sbrunner do we want to keep the `profile.csv` service in c2cgeoportal ?

**Comment by sbrunner** [comment]
Yes because it steel used by old CGXP applications :-)

**Comment by tsauerwein** [comment]
Thanks for the review, @fredj!

**Comment by stef74** [comment]
For me it's not work on iOS on chrome and safari. They show GPX file as a text but not usable (no way to export or open with dedicated app). On desktop I can save an reuse (so it usable).

**Comment by fredj** [comment]
You need an app that can open gpx file.

**Comment by stef74** [comment]
I have it .... If i open gpx file on my mail or google drive or other website it's work perfectly (it show open with ... and I can select my GPX app )

**Comment by sbrunner** [comment]
Your right, the main issue is here: 
https://github.com/eligrey/FileSaver.js/issues/12

**Comment by stef74** [comment]
But I have also the issue on chrome (on iOS).

**Comment by stef74** [comment]
on opera mini ... it open google search with blob:http://*******
on firefox : impossible to open the page. 

It'seem more IOS related ...

**Pull request merged**
