### PR TITLE
Translate tips from ol.control.Zoom

### LINKED ISSUE #919: Translate "Zoom in" and "Zoom out" ol3 button title

### PR DESCRIPTION
**Pull request by fredj**
fixes #919

### CODE REVIEW

**Comment by tsauerwein** [comment]
Will the tips also change when the language is changed?

**Comment by fredj** [comment]
Not automatically, needs a page reload

**Comment by fredj** [comment]
@sbrunner, @ybolognini is it a requirement that the tooltips change when the language is changed (without a page reload)?

And is it a requirement to have a tooltip for the zoom buttons ? there was no tooltips in 1.6

**Comment by sbrunner** [comment]
Will be replaced by #934

**Pull request closed without merging**
