### PR TITLE
Deactivate query tool when the draw panel is open

### LINKED ISSUE #1470: Query should be disabled when the redlining is open (and the print)
- open the redlining
- try to select a feature => a query is done ...

### PR DESCRIPTION
**Pull request by fredj**
fixes #1470 

https://fredj.github.io/ngeo/query_vs_draw/examples/contribs/gmf/apps/desktop/
https://fredj.github.io/ngeo/query_vs_draw/examples/contribs/gmf/apps/desktop_alt/

### CODE REVIEW

**Comment by sbrunner** [comment]
Don't seam to work with the print ...

**Comment by fredj** [comment]
I've updated the demo

**Comment by sbrunner** [comment]
Excellent, but we should be able to print the query results, it can be done in an other pull request...

Then that's looks good for me :-)

**Comment by ger-benjamin** [comment]
+1

**Comment by fredj** [comment]
I've removed the print from this pull request, new pull request to come

**Pull request merged**
