### PR TITLE
[backport 2.4] Translate layers names in API layer switcher

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@sbrunner : sorry, I missed that this was tagged 2.4 in JIRA

**Comment by arnaud-morvan** [comment]
@sbrunner : I do not manage to get travis green on the branch push, but it always success on PR.
I do not undestand, I'm already up to date with base branch.

**Comment by sbrunner** [comment]
Me neither => merge :-)

**Comment by arnaud-morvan** [comment]
As we cannot explain why up to date with 2.4 travis-ci/push fails without link to this PR content, whereas travis-ci/pr success, let's merge.

**Pull request merged**
