### PR TITLE
Be able to run the Webpack dev server in https

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by gberaudo** [comment]
@sbrunner, what domain your certificates use?
I would be reluctant to whitelist a localhost certificate, but a dedicated domain (ngeo, to wire in /etc/hosts would be fine).

**Comment by sbrunner** [comment]
localhost ...

**Comment by sbrunner** [comment]
For me a requirement to change /etc/hosts is not fine...

**Comment by gberaudo** [comment]
I am approving this change: while it is not a good habit to whitelist certificates, one should not input sensitive data to https://localhost...

**Pull request merged**
