### PR TITLE
Keep size ratio for legend icon

### PR DESCRIPTION
**Pull request by pgiraud**
Fixed in a very simple way. This breaks alignments though.

screenshot from 2016-06-14 16 25 32

@ybolognini please review.

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by pgiraud** [comment]
Fixes #1391.

**Comment by pgiraud** [comment]
@sbrunner this should not be merged back into master

**Comment by sbrunner** [comment]
effectively, done :-)

**Pull request merged**
