### PR TITLE
WIP - Upgrade to OpenLayers v3.20.0

### PR DESCRIPTION
**Pull request by adube**
Upgrade OpenLayers to v3.20.0.  Make all required fixes.

### CODE REVIEW

**Comment by adube** [comment]
Ready for review.  Although, like all the PRs I make lately, Travis fails with DEVELOPMENT mode enabled.

**Comment by adube** [comment]
Please, hold.  These changes may also need to be made.  See the "Upgrade notes".

https://github.com/openlayers/ol3/releases/tag/v3.20.0

**Comment by adube** [comment]
I don't understand why the compiler in ngeo wasn't able to detect this.  In other projects in which I include OpenLayers, I got the following errors that are valid with the new 3.20.0 version of OpenLayers:

```
ERR! compile myfile.js:152: ERROR - Function ol.Map.prototype.forEachFeatureAtPixel:
  called with 4 argument(s). Function requires at least 2 argument(s) and
  no more than 3 argument(s).
ERR! compile     var feature = map.forEachFeatureAtPixel(evt.pixel,
```

Just to let you know.

**Comment by adube** [comment]
This should cover everything, now.

**Comment by adube** [comment]
Still failing.

@gberaudo: reading your comment here: https://github.com/openlayers/ol3/pull/6207#issuecomment-265098046

It would seem it does affect ngeo's build:

```
ERR! compile node_modules/openlayers/externs/olx.js:5329: ERROR - Bad type annotation. Unknown type ol.source.Raster.OperationType
ERR! compile  *     operationType: (ol.source.Raster.OperationType|undefined)}}
ERR! compile                        ^
ERR! compile 
ERR! compile 
ERR! compile node_modules/openlayers/externs/olx.js:5377: ERROR - Bad type annotation. Unknown type ol.source.Raster.OperationType
ERR! compile  * @type {ol.source.Raster.OperationType|undefined}
ERR! compile           ^
ERR! compile 
ERR! compile 
ERR! compile 2
ERR! compile  error(s), 0 warning(s)
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 2 
```

as we include olx.js but we do not require `ol.source.Raster`, therefore this error is thrown.  I really thought that the upgrade to 3.20 would be simple, but I think it's out of my expertise.  I'll leave this up to someone else who wishes to carry on and I'll be very interested in seeing how this will be fixed.

**Comment by gberaudo** [comment]
@adube, see https://github.com/camptocamp/ngeo/tree/gb_upgrade-ol-3.20.0.

**Comment by adube** [comment]
Oh, I was expecting something more fancy.  I suppose that works, but doesn't that adds not needed files in the build?

Thank you very much for taking care of this.  I cherry-picked it here.

**Comment by gberaudo** [comment]
Seems there are more. I can have a look later today. Adding the require will make the file passed to the compiler but since the content is "not used" it should have no impact on the compiled file.

**Comment by sbrunner** [comment]
I do that to fix it:
https://github.com/camptocamp/ngeo/commit/c16a77bfb39dc32384b1d501f3f2008275d30e3f
Add the radius for the concern issue,
remove @api, it's ol only tag
remove @export no need to export that...

**Comment by gberaudo** [comment]
Thanks @sbrunner.

**Pull request closed without merging**
