### PR TITLE
Add a apidoc make target

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
please review, I will update he doc when #457 is merged

**Comment by sbrunner** [comment]
Is it relay required to build the apidoc in `.build/apidoc-$(GIT_BRANCH)`, can't it simply be in `.build/apidoc`?

**Comment by sbrunner** [comment]
>  I will update he doc when #457 is merged

The doc is generated automatically, it's not the case?

**Comment by fredj** [comment]
> I will update the doc when #457 is merged

Sorry, it wasn't clean: I will update the developer-guide when #457 is merged

**Comment by sbrunner** [comment]
ok :-)

**Comment by fredj** [comment]
> can't it simply be in `.build/apidoc`?

+1

**Comment by fgravin** [comment]
+1 too t
he `apidoc-[name]` doesn't make sense

**Pull request merged**
