### PR TITLE
Remove useless ngeo Query Service

### PR DESCRIPTION
**Pull request by ger-benjamin**
/!\ For 2.2
Fix https://github.com/camptocamp/ngeo/issues/3524
Was replaced by ngeo Querent and MapQuerent

Query works as before on apps and examples.

The gmf QueryManager was not used anymore and was based on ngeoService (marked as deprecated and not more used)

### CODE REVIEW

**Comment by ger-benjamin** [comment]
@rmichaelis @llienher It is still used by luxembourg, or by epfl ?
I don't think so, but to be sure that you are aware of this change...

**Comment by llienher** [comment]
Looks like the EPFL doesn't use this file, so fine for me.

**Comment by fredj** [comment]
> @fredj or by schweizmobil ?

not used by schweizmobil

**Comment by fredj** [comment]
thanks @ger-benjamin

**Pull request merged**
