### PR TITLE
Add missing require

### LINKED ISSUE #286: Missing requires
https://github.com/camptocamp/ngeo/blob/master/src/directives/map.js#L12
`goog.require('ol.Map');`

### PR DESCRIPTION
**Pull request by sbrunner**
fix #286

### CODE REVIEW

**Comment by elemoine** [comment]
In principle `goog.require('ol.Map')` will be added in the file where `ol.Map` is instantiated (i.e. in the application's `maincontroller.js` file). That being said, I don't think it harms to add it here as well. I am curious to know if that caused a real problem to you.

**Comment by sbrunner** [comment]
The main controller don't create a map https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/+package+/static-ngeo/js/maincontroller.js then be free to fix it as you want ...

**Comment by elemoine** [comment]
Yes, but it will. Or the `ngeo-gmf-map` directive will.

You can still merge this PR, as `ol.Map` is required for the lines including the typecast and the assertion.

**Comment by sbrunner** [comment]
OK, done, closing

**Comment by elemoine** [comment]
You did not merge it, did you?

**Comment by sbrunner** [comment]
No I will add it in the main controller as you suggest !
https://github.com/camptocamp/c2cgeoportal/commit/5db8b5f34e3e7047d085a8f66a9058e0a0a16693

**Comment by elemoine** [comment]
I also suggested to merge this PR. Please reread my comments.

**Comment by sbrunner** [comment]
Yes but as I understand you prefer not, finally I'm wrong ?

**Comment by elemoine** [comment]
> Yes but as I understand you prefer not, finally I'm wrong ?

Yes.

This is what I said:

"You can still merge this PR, as ol.Map is required for the lines including the typecast and the assertion."

The lines I am referring to are: https://github.com/camptocamp/ngeo/blob/master/src/directives/map.js#L32-L33.

**Comment by sbrunner** [comment]
ok :-)

**Pull request merged**
