### PR TITLE
Make the dimensions param in gmf-layertree optional

### LINKED ISSUE #1750: gmf-layertree: doesn't work if dimensions is not provided
The `dimensions` attribute of `gmf-layertree` should be optional.

The issue can be can be seen in this example:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/displayquerygrid.html

### PR DESCRIPTION
**Pull request by fredj**
fixes #1750

### CODE REVIEW

**Comment by ger-benjamin** [comment]
But dimension must always be there no  https://github.com/fredj/ngeo/blob/60a483e30c111829853d9a4591029532be3bcd34/contribs/gmf/src/directives/layertree.js#L93

Perhaps it's better to add someting like this:

in layertree controller:
`this.dimension = this.dimension | {}`

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by fredj** [comment]
@ger-benjamin I've updated to `=?gmfLayertreeDimensions`

**Comment by ger-benjamin** [comment]
Ok thanks. Please merge when travis is green

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
