### PR TITLE
Solve cyclic reference when printing imported KML

### PR DESCRIPTION
**Pull request by Jenselme**

### CODE REVIEW

**Comment by elemoine** [comment]
I think this is a bug in OpenLayers. The GeoJSON parser should not add a Style property to the GeoJSON feature.

**Comment by Jenselme** [comment]
For your information, I reported the issue in the ol3 bugtracker: https://github.com/openlayers/ol3/issues/3832

**Comment by Jenselme** [comment]
This is indeed a problem with openlayers, the issue is being solve there, no need for this patch. Closing.

**Comment by elemoine** [comment]
For reference, this problem was fixed in OpenLayers. https://github.com/openlayers/ol3/pull/3900

**Pull request closed without merging**
