### PR TITLE
Support map rotation for printing

### PR DESCRIPTION
**Pull request by Jenselme**

### CODE REVIEW

**Comment by Jenselme** [comment]
Travis build fails due to `ERR! compile /home/travis/build/camptocamp/ngeo/src/directives/search.js:71: ERROR - Bad type annotation. Unknown type jQuery.event`. If I run manually `macke check` on my computer, it works fine.

**Comment by pgiraud** [comment]
This is not due to your commit apparently. See https://github.com/camptocamp/ngeo/issues/230.

**Comment by pgiraud** [comment]
@Jenselme Can you please rebase your branch onto master?

**Comment by Jenselme** [comment]
Just rebase. Travis build is passing.

**Comment by elemoine** [comment]
@pgiraud feel free to merge this.

**Pull request merged**
