### PR TITLE
Escape string before using it as a regex

### PR DESCRIPTION
**Pull request by oterral**
Avoid a js error see https://github.com/geoadmin/mf-geoadmin3/issues/3785

### CODE REVIEW

**Comment by oterral** [comment]
The failure doesn't seem to be related to the code.

**Comment by sbrunner** [comment]
Why using a regexp for that?
We can't simply use `=` (or includes)?

**Comment by oterral** [comment]
No particular reason. We could use an other method too.

**Comment by sbrunner** [comment]
+1 for not using regex :-)

**Comment by oterral** [comment]
Removed

**Comment by gberaudo** [comment]
Thanks

**Pull request merged**
