### PR TITLE
[WIP] - manage 'deactivation' with unsaved changes in gmf-editfeature

### PR DESCRIPTION
**Pull request by adube**
This is work in progress for #1741.  It currently doesn't fix the issue and needs more work.

### CODE REVIEW

**Comment by adube** [comment]
@fredj Please, let me know your thoughts about this.

**Comment by fredj** [comment]
@adube see https://github.com/fredj/ngeo/commit/3fa49646af8448965f83400da162c38ba776969f
(still WIP)

The changes are now made in a `$timeout`; otherwise the changes are not taken into account (because they are made in a digest cycle)

**Comment by adube** [comment]
Understood.  I'm not sure where you're going with this but I'll follow this with lots of interest.

**Comment by fredj** [comment]
https://fredj.github.io/ngeo/1741-unsaved-modifications-deactivation/examples/contribs/gmf/apps/desktop

to test:
 - login as admin
 - select edit theme
 - open editing panel
 - draw a point
 - switch to print panel (or close panel)

-> the confirmation message is displayed

**Comment by adube** [comment]
+1

I'd like to be pointed out where the magic happens.  That's very cool.

**Comment by fredj** [comment]
@adube You code was correct; the only thing that didn't work was to change the value inside a `$watch`:
```js
$scope.$watch(function() {
  return this.active;
}.bind(this), function(active) {
  if (!active && this.dirty) {
    this.active = true;
  }
}.bind(this));
```

The change made inside the `$watch` is not _notified_ to the other listeners (other `$watch`) because the change occurs in a digest cycle.

**Comment by adube** [comment]
Cool.

Was this merged from somewhere else?  I noticed you closed the PR.

**Comment by fredj** [comment]
I opened #1856 (your changes + mine)

**Pull request closed without merging**
