### PR TITLE
Generate API documentation

### PR DESCRIPTION
**Pull request by sbrunner**
View result: http://camptocamp.github.io/ngeo/jsdoc/apidoc/

### CODE REVIEW

**Comment by asaunier** [comment]
Nice!
Is it possible to modify a bit the styles? It would be better if more space could be added in the right column after the "Classes" sections. Else it is a bit confusing to figure out what thoses classes are related to.

**Comment by sbrunner** [comment]
@asaunier done :-)

**Comment by elemoine** [comment]
There are still many problems to solve but this looks like a very good start!

**Comment by asaunier** [comment]
Thanks, that looks much better :)

**Comment by sbrunner** [comment]
> There are still many problems to solve but this looks like a very good start!

effectively :+1:

**Comment by elemoine** [comment]
The merge of this branch broke the build. The problem is related to the new mobileapp example missing a description or something. I'll look into it.

**Comment by elemoine** [comment]
https://camptocamp.github.io/ngeo/master/apidoc returns a 404. Is this expected?

**Comment by sbrunner** [comment]
I don't have a 404 your are probably faster than pages :-)

**Comment by elemoine** [comment]
Indeed.

**Pull request merged**
