### PR TITLE
Use 'key in obj' instead of 'goog.object.containsKey(obj, key)'

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by gberaudo** [comment]
+1. Can be simplified by removing the tests for `undefined`:
`undefined in {} -> false`

**Comment by fredj** [comment]
thanks @gberaudo, code updated

**Comment by sbrunner** [comment]
... I don't see any changes ...

**Comment by gberaudo** [comment]
There is actually a closure compilation issue when using `undefined`.
Thanks @fredj, LGTM for merging.

**Pull request merged**
