### PR TITLE
GMF-profile

### PR DESCRIPTION
**Pull request by ger-benjamin**
Part of: https://github.com/camptocamp/c2cgeoportal/issues/1661
Specs: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231661-Profiles#map---profile-interaction

Gmf example: https://ger-benjamin.github.io/ngeo/gmfprofile/examples/contribs/gmf/profile.html 
Doc: https://ger-benjamin.github.io/ngeo/gmfprofile/apidoc

Ngeo example (same as before but configuration as changed, was modified to accept multiple zExtractor): https://ger-benjamin.github.io/ngeo/gmfprofile/examples/profile.html

(Concrete integration example (wip): https://github.com/camptocamp/ngeo/pull/1480)

### CODE REVIEW

**Comment by ger-benjamin** [comment]
@pgiraud Can you take a look just on the style ? Don't review the code I'm currently in an auto-review.
(I know that's hard without Font-Awesome fonts...)

**Comment by pgiraud** [comment]
The style look very good to me.
Why not adding the font awesome css in the example?
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/layertree.html#L10

**Comment by ger-benjamin** [comment]
>Why not adding the font awesome css in the example?
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/layertree.html#L10

The Font-Awesome css is already in my example. The problem is more general in our build. See for instance (on the master):
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/layertree.html

**Comment by ger-benjamin** [comment]
Ready for a first review.

**Comment by fredj** [comment]
I'm not very familiar with the d3 profile code but looks good.
Do we know why the code coverage decreased?

**Comment by ger-benjamin** [comment]
>Do we know why the code coverage decreased?

Probably because I've added code on an absolutely no tested part of our code.

**Comment by ger-benjamin** [comment]
@fredj Do you think I can merge ? I'll can do others modifications on this next PR #1480 
IMO, the important point in this PR is that ngeo-profile (like used in the example) work always fine.

**Comment by fredj** [comment]
> Forget that, I've forgotten that I wait on closure-compiler... That can become a problem...

Yes but travis is green so the compiler is happy (?)

**Comment by ger-benjamin** [comment]
> Yes but travis is green so the compiler is happy (?)

... I don't explain that...
I'll try again soon on my machine..

**Comment by ger-benjamin** [comment]
I need to move on. Have I still something to do on the code or can I merge ?

**Comment by fredj** [comment]
please merge

**Pull request merged**
