### PR TITLE
Update code to match closure externs changes (ie. jQuery.Event)

### LINKED ISSUE #230: Build is broken
The build is broken on Travis: https://travis-ci.org/camptocamp/ngeo/builds/65867203.

```
node buildtools/build.js buildtools/ngeo.json dist/ngeo.js

info ol Parsing dependencies

info ol Compiling 391 sources

ERR! compile /home/travis/build/camptocamp/ngeo/src/directives/search.js:71: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile                * @param {jQuery.event} event Event.

ERR! compile                          ^

ERR! compile 

ERR! compile 

ERR! compile /home/travis/build/camptocamp/ngeo/src/directives/search.js:83: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile                * @param {jQuery.event} event Event.

ERR! compile                          ^

ERR! compile 

ERR! compile /home/travis/build/camptocamp/ngeo/src/directives/search.js:95: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile                * @param {jQuery.event} event Event.

ERR! compile                          ^

ERR! compile 

ERR! compile externs/ngeox.js:290: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  *   cursorchanged: (function(jQuery.event, Object,

ERR! compile                               ^

ERR! compile 

ERR! compile externs/ngeox.js:292: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  *   selected: (function(jQuery.event, Object,

ERR! compile                          ^

ERR! compile 

ERR! compile externs/ngeox.js:294: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  *   autocompleted: (function(jQuery.event, Object,

ERR! compile                               ^

ERR! compile 

ERR! compile externs/ngeox.js:314: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}

ERR! compile                    ^

ERR! compile 

ERR! compile externs/ngeox.js:320: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}

ERR! compile                    ^

ERR! compile 

ERR! compile externs/ngeox.js:326: ERROR - Bad type annotation. Unknown type jQuery.event

ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}

ERR! compile                    ^

ERR! compile 

ERR! compile 9 error(s), 0 warning(s)

ERR! compile 

ERR! Process exited with non-zero status, see log for more detail: 9 

make: *** [dist/ngeo.js] Error 1
```

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #230.

### CODE REVIEW

**Comment by gberaudo** [comment]
LGTM

**Comment by elemoine** [comment]
LGTMT.

**Comment by asaunier** [comment]
LGTMAW

**Comment by fredj** [comment]
unfortunately you can revert this commit now: https://github.com/google/closure-compiler/commit/b0aaa67e5cc08b51401b047c96f535bc94593eb4

**Comment by elemoine** [comment]
Oh boy!

**Pull request merged**
