### PR TITLE
Update openlayers and closure compiler to latest version

### PR DESCRIPTION
**Pull request by gberaudo**
Replaces #2109.

### CODE REVIEW

**Comment by fredj** [comment]
replace #2109 ?

**Comment by gberaudo** [comment]
@sbrunner I have an issue with the geomapfish demo:
```
node buildtools/build.js .build/examples/bboxquery.json .build/examples/bboxquery.js
info ol Parsing dependencies
info ol Compiling 524 sources
echo '//# sourceMappingURL=bboxquery.js.map' >> .build/examples/bboxquery.js
mkdir -p .build/examples-hosted/
cp .build/examples/bboxquery.js .build/examples-hosted/bboxquery.js
mkdir -p .build/examples-hosted/
sed -e 's|\.\./node_modules/openlayers/css/ol.css|lib/ngeo.css|' \
        -e 's|\.\./node_modules/bootstrap/dist/css/bootstrap.css|lib/bootstrap.min.css|' \
        -e 's|\.\./node_modules/font-awesome/css/font-awesome.css|lib/font-awesome.min.css|' \
        -e 's|\.\./node_modules/jquery/dist/jquery.js|lib/jquery.min.js|' \
        -e 's|\.\./third-party/jquery-ui/jquery-ui.min\.js|lib/jquery-ui.min.js|' \
        -e 's|\.\./third-party/jquery-ui/jquery-ui.min\.css|lib/jquery-ui.min.css|' \
        -e 's|\.\./node_modules/bootstrap/dist/js/bootstrap.js|lib/bootstrap.min.js|' \
        -e 's|\.\./node_modules/angular/angular.js|lib/angular.min.js|' \
        -e 's|\.\./node_modules/angular-animate/angular-animate.js|lib/angular-animate.min.js|' \
        -e 's|\.\./node_modules/angular-float-thead/angular-floatThead.js|lib/angular-floatThead.js|' \
        -e 's|\.\./node_modules/floatthead/dist/jquery.floatThead.min.js|lib/jquery.floatThead.min.js|' \
        -e 's|\.\./node_modules/angular-gettext/dist/angular-gettext.js|lib/angular-gettext.min.js|' \
        -e 's|\.\./node_modules/angular-touch/angular-touch.js|lib/angular-touch.min.js|' \
        -e 's|\.\./node_modules/angular-dynamic-locale/dist/tmhDynamicLocale.js|lib/tmhDynamicLocale.min.js|' \
        -e 's|\.\./node_modules/angular-ui-date/dist/date.js|lib/date.min.js|' \
        -e 's|\.\./node_modules/d3/d3.js|lib/d3.min.js|' \
        -e 's|\.\./node_modules/file-saver/FileSaver.min.js|lib/FileSaver.min.js|' \
        -e 's|\.\./node_modules/corejs-typeahead/dist/typeahead.bundle.js|lib/typeahead.bundle.min.js|' \
        -e 's|\.\./node_modules/proj4/dist/proj4\.js|lib/proj4.js|' \
        -e 's|\.\./node_modules/jsts/dist/jsts\.min\.js|lib/jsts.min.js|' \
        -e 's|/@?main=bboxquery.js|bboxquery.js|' \
        -e 's|default\.js|lib/transpile.js|' \
        -e 's|\.\./utils/watchwatchers.js|lib/watchwatchers.js|' \
        -e '/<head>/a\''    <script src="https.js"></script>''' examples/bboxquery.html > .build/examples-hosted/bboxquery.html
mkdir -p .build/
./node_modules/.bin/phantomjs --local-to-remote-url-access=true buildtools/check-example.js .build/examples-hosted/bboxquery.html
URL changed: file:///home/gberaudo/dev/ngeo/.build/examples-hosted/bboxquery.html
Resource error: 1, https://geomapfish-demo.camptocamp.net/1.6/wsgi/mapserv_proxy?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=bus_stop&CRS=EPSG%3A21781&STYLES=&WIDTH=900&HEIGHT=600&BBOX=447635%2C92640%2C627635%2C212640
Resource error: 1, https://geomapfish-demo.camptocamp.net/1.6/wsgi/mapserv_proxy?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=information&CRS=EPSG%3A21781&STYLES=&WIDTH=900&HEIGHT=600&BBOX=447635%2C92640%2C627635%2C212640
EXIT with 2
```
Could you please have a look to it?

**Comment by sbrunner** [comment]
It's working again :-)

**Comment by sbrunner** [comment]
Is this line steel working?
https://github.com/camptocamp/ngeo/blob/master/Makefile#L49

**Comment by gberaudo** [comment]
Thanks @sbrunner. I have rebased, will merge as soon as it is green.

**Pull request merged**
