### PR TITLE
[Work in progress] New ngeo.interaction.MeasureCoordinate

### PR DESCRIPTION
**Pull request by fredj**
Related to https://github.com/camptocamp/c2cgeoportal/issues/1671

### CODE REVIEW

**Comment by ger-benjamin** [comment]
It's still a WIP ?
It seems to work fine. (Even if the tooltips messages should be improved.)

**Comment by fredj** [comment]
It's still in WIP because we don't know if our client wants it

**Comment by sbrunner** [comment]
Is it got GeoMapFish?

**Comment by ger-benjamin** [comment]
@fredj  Can we add a milestone on this PR ? And perhaps a label/assignee/issue ?

**Comment by sbrunner** [comment]
This it not for GeoMapFish => No milestone, no label :-)

**Pull request closed without merging**
