### PR TITLE
Use the feature overlay manager for drawings

### LINKED ISSUE #1349: Drawing not displayed in PDF
Looks like drawing isn't displayed in PDF. Instead there is some kind of whitish layer on top of map.

### PR DESCRIPTION
**Pull request by pgiraud**
Helps drawings being printed.

Fixes #1349.

 WIP. I could not test it.
Démo: https://pgiraud.github.io/ngeo/print_drawing/examples/contribs/gmf/apps/desktop

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by ger-benjamin** [comment]
+1

**Comment by pgiraud** [comment]
The demo is working.
Merging. Thanks for the reviews.

**Comment by pgiraud** [comment]
I just noticed that the print service doesn't support labels.
Error looks like "java.lang.NumberFormatException: For input string: "10pt". Where should I report this issue?

**Pull request merged**
