### PR TITLE
Use ol.events instead of goog.events

### PR DESCRIPTION
**Pull request by fredj**
Needs tests

### CODE REVIEW

**Comment by sbrunner** [comment]
You should also update openlayers ...

**Comment by fredj** [comment]
> You should also update openlayers ...

but do we want to go back to ol3 master ?

**Comment by sbrunner** [comment]
(or an hash) temporary yes because @adube as needs an unreleased version...

**Comment by adube** [comment]
Can we merge this soon ?

**Comment by fredj** [comment]
Let's go

**Comment by petzlux** [comment]
Is this breaking our build ? https://travis-ci.org/Geoportail-Luxembourg/geoportailv3/builds/107210332

**Pull request merged**
