### PR TITLE
Fix the ol3 commit

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by tsauerwein** [comment]
Have you tested if you can build? See https://github.com/camptocamp/ngeo/pull/1180#issuecomment-218204325

**Comment by sbrunner** [comment]
Effectively https://travis-ci.org/camptocamp/ngeo/jobs/129185045#L763 :-(

**Comment by fredj** [comment]
I'm on it

**Comment by fredj** [comment]
BTW, the travis error is not related to this change

**Comment by sbrunner** [comment]
?

**Pull request closed without merging**
