### PR TITLE
Sed commands compatible with Mac (round 2)

### LINKED ISSUE #662: weird $ characters in hosted examples
@sbrunner you were right.
The following commit doesn't work correctly on Linux.
https://github.com/pgiraud/ngeo/commit/a08050f777a41bd889e4fbc5bf9dbd16fe8c5ed8

Extra "$" characters are added at the bottom of the page.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #662.

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by pgiraud** [comment]
The build fails because the coverage increased (+0.0%). What am I supposed to do in this case?

**Comment by tsauerwein** [comment]
> The build fails because the coverage increased (+0.0%). What am I supposed to do in this case?

Remove tests!

**Comment by tsauerwein** [comment]
No, seriously. Currently the Coverage threshold is configured not to fall below 35%. I guess another PR pulled the coverage down. I guess we have to readjust.

**Comment by sbrunner** [comment]
Coveralls configurations adjusted to 30% of minimum coverage for the next runs...

**Pull request merged**
