### PR TITLE
Add more closure-compiler checks

### LINKED ISSUE #440: No check for unused 'goog.require's
When building there is no check for unused `goog.require`s like in ol3:
https://github.com/openlayers/ol3/blob/master/bin/check-requires.py#L120-L123

### PR DESCRIPTION
**Pull request by fredj**
Fixes #440

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good, thanks :-)

**Comment by fgravin** [comment]
What the new comments with `@suppress` for ?

**Comment by fredj** [comment]
`@suppress {extraRequire}` tells the compiler to not check the next `goog.require`.

Example:
In `src/services/popup.js` we require `ngeo.popupDirective`. The checker expect that `ngeo.popupDirective.*` is used in the file but that not the case.

**Comment by fgravin** [comment]
Oh ok, so it's mainly for directives requires.

**Comment by sbrunner** [comment]
This should be rebased and merged :-)

**Pull request merged**
