### PR TITLE
Use a transofrmUrl function also in import dnd component

### PR DESCRIPTION
**Pull request by oterral**

### CODE REVIEW

**Comment by gberaudo** [comment]
@oterral, Travis is failing.

**Comment by oterral** [comment]
I've fixed lint issues but I'm not sur why the build still failed.

**Comment by fredj** [comment]
@oterral was broken, please rebase

**Comment by fredj** [comment]
> @oterral was broken, please rebase

the master branch was broken, not you :-)

**Comment by oterral** [comment]
:)

**Comment by gberaudo** [comment]
Thanks

**Pull request merged**
