### PR TITLE
Correct name of dimensions parameters to meet MapFish Print expectations

### PR DESCRIPTION
**Pull request by Jenselme**

### CODE REVIEW

**Comment by elemoine** [comment]
Out of curiosity, is there some MapFish Print documentation about this?

**Comment by sbrunner** [comment]
That looks a hack to hide an other issue, ol3 and Mapfish-print should work with the same case, if not it's probably an issue on one of them...

**Comment by Jenselme** [comment]
I completely forgot this PR, sorry. @elemoine I don't think there is documentation in MFP about this or I can't see it: http://mapfish.github.io/mapfish-print-doc/#/mapLayer#record%2F%20Tiled%20Wms%20Layer%2Ftitle

@sbrunner It may indeed hide an other issue. From what I know, ol uses the `Time` format. It also looks to be the `WMTS` of doing things from what I see in capabilities.xml.

Maybe I should dig into it again and post my findings here. If any of you have an idea/opinion about that, please share.

**Comment by Jenselme** [comment]
I managed to get a quick look again today.

With the current code of ngeo, I get:
- Dimensions : `{ Time: "20081024" }`
- Dimensions keys: `[ "Time" ]`

In the browser:
```
Error while processing request:
org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.map.layers[0].dimensionParams.TIME] missing
```

In MFP logs:
```
14:46:30.539 [http-apr-8080-exec-10] INFO  o.m.p.s.job.ThreadPoolJobManager - Submitted print job fdb58635-9582-4317-bd4e-e535f38f9c28@1efea52a-f7cc-48b0-808b-7463e048dc58
14:46:30.543 [PrintJobManager-5] INFO  o.mapfish.print.servlet.job.PrintJob - Starting print job fdb58635-9582-4317-bd4e-e535f38f9c28@1efea52a-f7cc-48b0-808b-7463e048dc58
14:46:30.552 [PrintJobManager-5] INFO  o.mapfish.print.servlet.job.PrintJob - Error executing print job fdb58635-9582-4317-bd4e-e535f38f9c28@1efea52a-f7cc-48b0-808b-7463e048dc58
spec:
	{"layout":"A4 portrait","app":"geojb","attributes":{"printLegend":0,"requestHeaders":{"requestHeaders":{"referer":["http://localhost/?topic=01_cadastre&lang=fr&bgLayer=voidLayer&layers=CADASTRE,WMTS%7C%7Cch.blw.ursprungsbezeichnungen-kaese%7C%7CTime:20081024%7C%7Chttps:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2FWMTSCapabilities.xml&catalogNodes="],"content-length":["5021"],"accept-language":["en-US,en;q=0.5"],"origin":["http://localhost"],"dnt":["1"],"x-forwarded-for":["127.0.0.1"],"pragma":["no-cache"],"accept":["application/json, text/plain, */*"],"x-forwarded-server":["pserve.geojb"],"x-forwarded-host":["pserve.geojb"],"host":["localhost:8080"],"content-type":["application/json; charset=UTF-8"],"connection":["Keep-Alive"],"cache-control":["no-cache"],"accept-encoding":["gzip, deflate"],"user-agent":["Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"]}},"legend":{},"bottomLeftCornerCoords":"x = 578054, y = 217908","commune":"Pery-La Heutte - Péry","name":"Ma carte","qrimage":"http://pserve.geojb/qrcodegenerator?url=http%3A%2F%2Flocalhost%2F%3Ftopic%3D01_cadastre%26lang%3Dfr%26bgLayer%3DvoidLayer%26layers%3DCADASTRE%2CWMTS%257C%257Cch.blw.ursprungsbezeichnungen-kaese%257C%257CTime%3A20081024%257C%257Chttps%3A%252F%252Fwmts.geo.admin.ch%252F1.0.0%252FWMTSCapabilities.xml%26catalogNodes%3D","scale":75000,"map":{"center":[585000,227500],"rotation":0,"layers":[{"imageFormat":"image/png","matrixSet":"21781_26","baseURL":"https://wmts.geo.admin.ch/1.0.0/ch.blw.ursprungsbezeichnungen-kaese/default/{Time}/21781/{TileMatrix}/{TileRow}/{TileCol}.png","requestEncoding":"REST","style":"ch.blw.ursprungsbezeichnungen-kaese","matrices":[{"identifier":"0","topLeftCorner":[420000,350000],"matrixSize":[1,1],"scaleDenominator":1.42857505715E7,"tileSize":[256,256]},{"identifier":"1","topLeftCorner":[420000,350000],"matrixSize":[2,2],"scaleDenominator":1.33928911608E7,"tileSize":[256,256]},{"identifier":"2","topLeftCorner":[420000,350000],"matrixSize":[4,4],"scaleDenominator":1.25000317501E7,"tileSize":[256,256]},{"identifier":"3","topLeftCorner":[420000,350000],"matrixSize":[8,8],"scaleDenominator":1.16071723393E7,"tileSize":[256,256]},{"identifier":"4","topLeftCorner":[420000,350000],"matrixSize":[16,16],"scaleDenominator":1.07143129286E7,"tileSize":[256,256]},{"identifier":"5","topLeftCorner":[420000,350000],"matrixSize":[32,32],"scaleDenominator":9821453.51791,"tileSize":[256,256]},{"identifier":"6","topLeftCorner":[420000,350000],"matrixSize":[64,64],"scaleDenominator":8928594.10719,"tileSize":[256,256]},{"identifier":"7","topLeftCorner":[420000,350000],"matrixSize":[128,128],"scaleDenominator":8035734.696470001,"tileSize":[256,256]},{"identifier":"8","topLeftCorner":[420000,350000],"matrixSize":[256,256],"scaleDenominator":7142875.28575,"tileSize":[256,256]},{"identifier":"9","topLeftCorner":[420000,350000],"matrixSize":[512,512],"scaleDenominator":6250015.87503,"tileSize":[256,256]},{"identifier":"10","topLeftCorner":[420000,350000],"matrixSize":[1024,1024],"scaleDenominator":5357156.46431,"tileSize":[256,256]},{"identifier":"11","topLeftCorner":[420000,350000],"matrixSize":[2048,2048],"scaleDenominator":4464297.05359,"tileSize":[256,256]},{"identifier":"12","topLeftCorner":[420000,350000],"matrixSize":[4096,4096],"scaleDenominator":3571437.64288,"tileSize":[256,256]},{"identifier":"13","topLeftCorner":[420000,350000],"matrixSize":[8192,8192],"scaleDenominator":2678578.23216,"tileSize":[256,256]},{"identifier":"14","topLeftCorner":[420000,350000],"matrixSize":[16384,16384],"scaleDenominator":2321434.46787,"tileSize":[256,256]},{"identifier":"15","topLeftCorner":[420000,350000],"matrixSize":[32768,32768],"scaleDenominator":1785718.82144,"tileSize":[256,256]},{"identifier":"16","topLeftCorner":[420000,350000],"matrixSize":[65536,65536],"scaleDenominator":892859.410719,"tileSize":[256,256]},{"identifier":"17","topLeftCorner":[420000,350000],"matrixSize":[131072,131072],"scaleDenominator":357143.764288,"tileSize":[256,256]},{"identifier":"18","topLeftCorner":[420000,350000],"matrixSize":[262144,262144],"scaleDenominator":178571.882144,"tileSize":[256,256]},{"identifier":"19","topLeftCorner":[420000,350000],"matrixSize":[524288,524288],"scaleDenominator":71428.7528575,"tileSize":[256,256]},{"identifier":"20","topLeftCorner":[420000,350000],"matrixSize":[1048576,1048576],"scaleDenominator":35714.3764288,"tileSize":[256,256]},{"identifier":"21","topLeftCorner":[420000,350000],"matrixSize":[2097152,2097152],"scaleDenominator":17857.1882144,"tileSize":[256,256]},{"identifier":"22","topLeftCorner":[420000,350000],"matrixSize":[4194304,4194304],"scaleDenominator":8928.59410719,"tileSize":[256,256]},{"identifier":"23","topLeftCorner":[420000,350000],"matrixSize":[8388608,8388608],"scaleDenominator":7142.875285749999,"tileSize":[256,256]},{"identifier":"24","topLeftCorner":[420000,350000],"matrixSize":[16777216,16777216],"scaleDenominator":5357.15646431,"tileSize":[256,256]},{"identifier":"25","topLeftCorner":[420000,350000],"matrixSize":[33554432,33554432],"scaleDenominator":3571.4376428799997,"tileSize":[256,256]},{"identifier":"26","topLeftCorner":[420000,350000],"matrixSize":[67108864,67108864],"scaleDenominator":1785.7188214399998,"tileSize":[256,256]}],"opacity":1,"type":"WMTS","dimensionParams":{"Time":"20081024"},"version":"1.0.0","layer":"ch.blw.ursprungsbezeichnungen-kaese","dimensions":["Time"]},{"imageFormat":"image/png","baseURL":"http://mapserver.local/wms/geojb?","customParams":{"TRANSPARENT":true,"MAP.RESOLUTION":300},"layers":["CADASTRE"],"type":"wms","opacity":1}],"scale":75000,"projection":"EPSG:21781","dpi":300},"url":"http://localhost/?topic=01_cadastre&lang=fr&bgLayer=voidLayer&layers=CADASTRE,WMTS%7C%7Cch.blw.ursprungsbezeichnungen-kaese%7C%7CTime:20081024%7C%7Chttps:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2FWMTSCapabilities.xml&catalogNodes="},"outputFormat":"pdf"}
org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.map.layers[0].dimensionParams.TIME] missing
	at org.mapfish.print.wrapper.PAbstractObject.getString(PAbstractObject.java:48) ~[classes/:na]
	at org.mapfish.print.map.tiled.wmts.WMTSLayer.createRestURI(WMTSLayer.java:197) ~[classes/:na]
	at org.mapfish.print.map.tiled.wmts.WMTSLayerParam.validateBaseUrl(WMTSLayerParam.java:171) ~[classes/:na]
	at org.mapfish.print.map.tiled.wmts.WMTSLayerParam.postConstruct(WMTSLayerParam.java:140) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.mapfish.print.parser.MapfishParser.parse(MapfishParser.java:141) ~[classes/:na]
	at org.mapfish.print.attribute.map.GenericMapAttribute$GenericMapAttributeValues.parseSingleLayer(GenericMapAttribute.java:307) ~[classes/:na]
	at org.mapfish.print.attribute.map.GenericMapAttribute$GenericMapAttributeValues.parseLayers(GenericMapAttribute.java:286) ~[classes/:na]
	at org.mapfish.print.attribute.map.GenericMapAttribute$GenericMapAttributeValues.postConstruct(GenericMapAttribute.java:275) ~[classes/:na]
	at org.mapfish.print.attribute.map.MapAttribute$MapAttributeValues.postConstruct(MapAttribute.java:142) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.mapfish.print.parser.MapfishParser.parse(MapfishParser.java:141) ~[classes/:na]
	at org.mapfish.print.output.Values.populateFromAttributes(Values.java:198) ~[classes/:na]
	at org.mapfish.print.output.Values.<init>(Values.java:130) ~[classes/:na]
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:151) ~[classes/:na]
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:109) ~[classes/:na]
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:138) ~[classes/:na]
	at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:142) ~[classes/:na]
	at org.mapfish.print.servlet.job.FilePrintJob.withOpenOutputStream(FilePrintJob.java:50) ~[classes/:na]
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:139) [classes/:na]
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:56) [classes/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
14:46:31.815 [http-apr-8080-exec-3] ERROR o.m.print.servlet.BaseMapServlet - Error while processing request: org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.map.layers[0].dimensionParams.TIME] missing
```

So obviously MFP expects the dimensions params to be uppercase. I look again today at the documentation and I found [the relevant part](http://mapfish.github.io/mapfish-print-doc/#/mapLayer#record%2FWMTS%20Layer%2Ftitle):

>  **dimensionParams**
>
> Dictionary of dimensions name (Must be uppercase) => value.

This is confirmed by a [comment in the code of MFP](https://github.com/mapfish/mapfish-print/blob/2e2b6b0f7849d859acb81cb8d73b9c57bee2544c/core/src/main/java/org/mapfish/print/map/tiled/wmts/WMTSLayerParam.java#L101).

So ol and MFP have different behavior regarding this point. Since in WMTS urls it seems that `Time` is use instead of `TIME`, I think this should be addressed in MFP. I think it should force this string to be uppercased. From what I understand, something similar is done for the values of WMTS dimensions: https://github.com/mapfish/mapfish-print/blob/2e2b6b0f7849d859acb81cb8d73b9c57bee2544c/core/src/main/java/org/mapfish/print/map/tiled/wmts/WMTSLayer.java#L197

What do you think?

**Comment by sbrunner** [comment]
I think that's a MapFish Print issue, I just report it here: https://github.com/mapfish/mapfish-print/issues/348

**Comment by sbrunner** [comment]
Fixed in Mapfish Print then closing :-)

**Pull request closed without merging**
