### PR TITLE
Prevent default action on click on anchor link.

### PR DESCRIPTION
**Pull request by blattmann**
Fix disables displaying the href (anchor) values in the browser's address bar.

### CODE REVIEW

**Comment by blattmann** [comment]
Issue URL: https://github.com/camptocamp/c2cgeoportal/issues/1979

**Comment by fgravin** [comment]
```html
<a href="#background" data-toggle="slide-in" ng-click="$event.preventDefault()">
```

Can you try instead and see if it works or not.

```html
<a href="" target="#background" data-toggle="slide-in">
```

**Comment by blattmann** [comment]
<a href="" target="#background" data-toggle="slide-in"> does not work.

**Comment by fgravin** [comment]
http://getbootstrap.com/javascript/#via-data-attributes-1

`data-target` maybe ?

**Comment by blattmann** [comment]
nope. sorry.

**Comment by sbrunner** [comment]
Why not using buttons?

**Comment by fgravin** [comment]
I've tried

```js
            // element to slide in
            var slideIn = $($(this).attr('target'));
```

```html
            <a href="" target="#background" data-toggle="slide-in">Background</a>
```

Works well.
See https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/mobilenav.js#L91

Do you agree @pgiraud ?

**Comment by pgiraud** [comment]
@fgravin looks like a nice solution. To make it more compatible, I would even prefix the attribute "data-".

**Comment by fgravin** [comment]
@blattmann please do the change as mentionned. use `data-target`.

**Comment by blattmann** [comment]
If I do the changes as you proposed then it works fine in the address bar of the browser (does not show the anchor links) but the panel also does not show any more info regarding the backgrounds or the themes.

Here the code:
`<a href="" data-target="#background" data-toggle="slide-in">Background</a>`
`<a href="" data-target="#themes" data-toggle="slide-in">Themes</a>`

See my short screencast:
[https://drive.google.com/file/d/0B2m6lBH9E2lgbzVUMHNBTDI3b3M/view?usp=sharing](url)

**Comment by pgiraud** [comment]
Replaced by #672.

**Pull request closed without merging**
