### PR TITLE
datepicker

### PR DESCRIPTION
**Pull request by ger-benjamin**
To use a jquery-ui datepicker

### CODE REVIEW

**Comment by asaunier** [comment]
Perhaps you could make your commit comment more explicit?

**Comment by ger-benjamin** [comment]
You're right, thanks (and done)

**Comment by asaunier** [comment]
Looks good to me.
(or maybe ``jQuery Datepicker`` => ``jQuery UI Datepicker``?)

**Comment by ger-benjamin** [comment]
Thanks. Note: I think this is ``jQuery.prototype`` and not ``jQueryUI.prototype`` because jQueryUI functions seem to be added directly at jQuery. Only some "jquery-ui" objects are not in the jQuery object (but are in object ``jQuery.ui``)

**Comment by fredj** [comment]
please merge

**Pull request merged**
