### PR TITLE
Make the search placeholder configurable

### PR DESCRIPTION
**Pull request by fredj**
TODO: the `Search…` string is not translated 

edit: it's now fixed

### CODE REVIEW

**Comment by tsauerwein** [comment]
> TODO: the Search… string is not translated

For c2corg we are using `x-translate`. `x-translate` is not extracted as translatable string, but Angular recognizes it.

**Comment by tsauerwein** [comment]
(Though that doesn't work together with `placeholder`.)

**Comment by tsauerwein** [comment]
Other idea: Create a custom filter `translate-no-extracted` which internally uses `translate` but which is not extracted by `gettext`.

**Comment by fredj** [comment]
I have to check but I suspect `gettextCatalog.getString` to happen to early (before the remote json are loaded)

**Comment by fredj** [comment]
`gettextCatalog.getString` was indeed called before the remote json file were processed.

**Comment by fredj** [comment]
The solution was to use `placeholder="{{ctrl.placeholder || 'Search…' | translate}}`

**Comment by gberaudo** [comment]
LGTM

**Comment by gberaudo** [comment]
Out of curiosity, do someone knows why the search directive is not bound to the controller?

**Comment by fredj** [comment]
> Out of curiosity, do someone knows why the search directive is not bound to the controller?

I don't know but I don't see any god reason ...

**Pull request merged**
