### PR TITLE
Avoid leaving search field if searing coordinates

### PR DESCRIPTION
**Pull request by marionb**
fixes c2c issue #[2294](https://github.com/camptocamp/c2cgeoportal/issues/2294)

### CODE REVIEW

**Comment by sbrunner** [comment]
Can you provide a demo link?

**Comment by marionb** [comment]
Link to demo: https://marionb.github.io/ngeo/search_focus/examples/contribs/gmf/apps/desktop/index.html?lang=en

**Comment by ger-benjamin** [comment]
LGTM. Thanks !

**Comment by ger-benjamin** [comment]
Edit: Just ask (someone ?) if that's not a spec in the mobile part.

**Comment by sbrunner** [comment]
Effectively, we have an issue on the mobile, shouldn't we hide the mask on this case?

**Comment by sbrunner** [comment]
@pgiraud what do you think about this?

**Comment by ger-benjamin** [comment]
@marionb Can we close this PR ? Because of https://github.com/camptocamp/ngeo/pull/1560

**Pull request closed without merging**
