### PR TITLE
Allow injection of gmfObjectEditingManager to fail in Permalink

### LINKED ISSUE #2844: Non working gmf example
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/elevation.html
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/drawfeature.html

Error is:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.6.6/$injector/unpr?p0=gmfLayersUrlProvider%20%3C-%20gmfLayersUrl%20%3C-%20gmfEditFeature%20%3C-%20gmfObjectEditingManager%20%3C-%20gmfPermalink
```

### PR DESCRIPTION
**Pull request by pfirpfel**
Fixes #2844 

Not sure if try/catch is a good practice.

### CODE REVIEW

**Comment by ger-benjamin** [comment]
Mhh the try catch is useless. You use already a "if" statement on the "$injector.has" function.
If it doesn't have the object, you can assign a "null" value in the else.

**Comment by pfirpfel** [comment]
That's not what I observed. The $injector.has returns true regardless of whether the $injector.get will succeed or not.
The injection does not fail directly at the gmf.ObjectEditingManager, it fails upwards in the "injection-chain" in gmf.EditFeature.

**Comment by pfirpfel** [comment]
These are the previous attempts to fix this issue:
#2846
#2873

**Comment by ger-benjamin** [comment]
It's probably not easy, but I think that's not good to **catch** the issue, we should take time to **resolve** the issue (If I understand correctly, in the gmf.EditFeature)

**Comment by pfirpfel** [comment]
I tried that in #2873. But @sbrunner thinks it shoudl be the other way around, it should be resolved from Permalink.

**Comment by ger-benjamin** [comment]
Okay... so I don't know what to do. @fredj ?

**Comment by fredj** [comment]
I've also tried in #2846 but @sbrunner said that it broke the build in docker

**Comment by sbrunner** [comment]
In the permalink the `gmf.ObjectEditingManager` requirement should be removes and replaced by an interface, to be able to call the `getFeature`...

**Comment by ger-benjamin** [comment]
It seems that the removal of "goog.require('gmf.ObjectEditingManager');" in the permalink is enough.

**Comment by pfirpfel** [comment]
This apparently [breaks a docker build](https://github.com/camptocamp/ngeo/pull/2846#issuecomment-325644123).

**Comment by sbrunner** [comment]
Probably because he in't replaced by an interface...

**Comment by pfirpfel** [comment]
#3157 removes the gmfObjectEditingManager require

**Comment by pfirpfel** [comment]
#3157 fixes this issue

**Pull request closed without merging**
