### PR TITLE
Remove the div around gmf-search element

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
@pgiraud can you please take a look ?

**Comment by fredj** [comment]
@ger-benjamin can you please take a look ?

**Comment by ger-benjamin** [comment]
What is the aim of this PR ? (fix or prevent what ?)
And can you make a gh-pages with this ? I think that we can have a css issue with that.

**Comment by fredj** [comment]
> What is the aim of this PR ? (fix or prevent what ?)

Simplify the code in *.html files and simplify the dom tree

**Comment by fredj** [comment]
> And can you make a gh-pages with this ? I think that we can have a css issue with that.

https://camptocamp.github.io/ngeo/rm_div_search/examples/contribs/gmf/apps/mobile/
https://camptocamp.github.io/ngeo/rm_div_search/examples/contribs/gmf/apps/desktop/
https://camptocamp.github.io/ngeo/rm_div_search/examples/contribs/gmf/apps/desktop_alt/

**Comment by ger-benjamin** [comment]
Thanks, and nice catch.
Please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
