### PR TITLE
Ensure node comments are not messed up after drop at same location

### LINKED ISSUE #1744: All groups are deleted after moving a group
To reproduce:
- OSM theme on "desktop" example
- Keeping mouse button down, start to move top group
- Keeping mouse button down, move the group down and up a little
- Move the group back to top place, release mouse button
- Click on "remove" button, all groups are deleted!

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #1744.

### CODE REVIEW

**Comment by pgiraud** [comment]
Sorry still some checks errors to fix.

**Comment by pgiraud** [comment]
Please review.
Demo: https://pgiraud.github.io/ngeo/fix-sortable/examples/contribs/gmf/apps/desktop

**Comment by ger-benjamin** [comment]
There is always an issue. Try to move around the first item then drop it at the second place.
Delete it: all elements after will be deleted.

**Comment by pgiraud** [comment]
OK. My pull request fixes only one part. There are 2 different issues.

@ger-benjamin provided an example showing that things are messed up when dropping an element at the same place.
See https://ger-benjamin.github.io/ngeo/repeatError/examples/contribs/gmf/repeaterror.html

With my patch applied, the "drop-to-same-location" issue is fixed:
https://pgiraud.github.io/ngeo/repeatError/examples/contribs/gmf/repeaterror.html

In the GMF layertree, this is also fixed.

But as @ger-benjamin reported, there's an other case which is not correctly handled. It's a completely separate issue though. Because we use a different property for the `ngeo-sortable` and the `ng-repeat` (`gmfLayertreeCtrl.layers` vs. `layertreeCtrl.node.children`), the `ng-repeat` doesn't detect changes properly and doesn't rebuild the DOM.
With the up-coming refactoring on the tree, I hope we will eventually use the same property for both which will fix the issue.

**Comment by ger-benjamin** [comment]
Yes. So then, for me, this problem is fixed. You can merge.

**Comment by sbrunner** [comment]
@pgiraud up ?

**Comment by pgiraud** [comment]
People from the Luxembourg geoportal application confirmed that https://github.com/Geoportail-Luxembourg/geoportailv3/issues/1423 gets fixed with the current pull request. Merging.

**Pull request merged**
