### PR TITLE
Change layertree icons for layers.

### PR DESCRIPTION
**Pull request by blattmann**
Leaf nodes (layer) icon is changed.

### CODE REVIEW

**Comment by blattmann** [comment]
Test:
https://blattmann.github.io/ngeo/#644_layer_tree_icons/examples/contribs/gmf/apps/mobile/

**Comment by sbrunner** [comment]
404 not found ...

**Comment by blattmann** [comment]
was too early with the link ;) sorry. i cannot build the example as i run into an error. so just ignore that link please.

**Comment by blattmann** [comment]
As I cannot provide a real example I will provide at least a screenshot:

screen shot 2016-02-18 at 17 52 40

**Comment by pgiraud** [comment]
This does not match what I specified.
And the group icons disappeared.

**Comment by pgiraud** [comment]
Addresses #644.

**Comment by ger-benjamin** [comment]
rework on PR: https://github.com/camptocamp/ngeo/pull/731

**Pull request closed without merging**
