### PR TITLE
IE11 doesnt consistently size the popover box.

### PR DESCRIPTION
**Pull request by ochriste**
So we need to set a min width rule to force it.

fix  https://jira.camptocamp.com/browse/GEO-609

### CODE REVIEW

**Comment by pfirpfel** [comment]
Fixes #3011

**Comment by pfirpfel** [comment]
The look doesn't change now, it stays like this:
selection_063

Do you think, you could also fix the height of the box?

On other browsers, there is much less empty space:
selection_064

**Comment by ochriste** [comment]
the space is because of the show/hide legend item
I can try to fix that

**Comment by sbrunner** [comment]
Not present on 2.2?

**Pull request merged**
