### PR TITLE
Fix less imports

### PR DESCRIPTION
**Pull request by sbrunner**
I have to split the `mobile.less` in two parts because `less.js` creates the links from the first included less file.

### CODE REVIEW

**Comment by sbrunner** [comment]
Visible at: http://camptocamp.github.io/ngeo/fix-less/examples/contribs/gmf/apps/mobile/index.html

**Comment by fgravin** [comment]
Maybe `build.less` is not very relevant for name, what do you think ?

**Comment by sbrunner** [comment]
I don't know, do you have a better purpose?
`for_build.less`?

**Comment by fgravin** [comment]
Ok nevermind i don't think we can get any better.
It is good for me, you can merge.

**Comment by sbrunner** [comment]
Thanks @fgravin

**Pull request merged**
