### PR TITLE
Update reference base images

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Review by ger-benjamin — APPROVED** [review]
Thanks please merge.

**Review by ger-benjamin — COMMENTED** [review]
It is related to you polygon changes ?
Should we update the 2.5 too ?

**Review by sbrunner — APPROVED** [review]

**Comment by arnaud-morvan** [comment]
@ger-benjamin :  Pretty sure geodata are not shared between GMF 2.5 / 2.6 demos.

**Comment by ger-benjamin** [comment]
Yes, very probably not shared, but I was wondering if you have done some modification on the 2.5 too.
I guess no

**Comment by arnaud-morvan** [comment]
My modifications on polygons was to solve this issue, but seems there was other differences.
We might discuss at the daily how to avoid such issues, for example by using dedicated layers for the example checks, here maybe on 2.6 and 2.5.

**Pull request merged**
