### PR TITLE
Remove force center after view animation.

### PR DESCRIPTION
**Pull request by ger-benjamin**
For https://camptocamp.atlassian.net/browse/GSSCHWYZ-429
And https://github.com/camptocamp/GeoMapFish/issues/92

But will break (origin): https://camptocamp.atlassian.net/browse/GSGMF-2009
Who looks to be a issue on a particular GMF.

This workaround was making the map less blurry in case of map height with a not round number of pixels, but it cause the map zoom to "jump" if the view.contrainResolution is set to true.

My idea is to trash this function, and let the concerned GMF implement it on need.

Another possibility would be keep the function in the code but not active by default (let the user choose if he want to use it).

Or to add a options in the vars to activate it or not.

If we keep it we could also add a debounce to to not recenter too quickly.

[Examples](https://camptocamp.github.io/ngeo/refs/pull/9541/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9541/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9541/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9541/merge/apidoc/)

### CODE REVIEW

**Comment by sbrunner** [comment]
This code is required to don't get bury tiles, this should be activated by default, we can add an option to be able to disable it.

**Comment by ger-benjamin** [comment]
I've tried several on different configuration to reproduce the "blurry effect", even with the commit before the original fix, but I was not able to see any difference. If we had a map quality issue with OpenLayers 7, there are good chance that it's fixed now. Therefor, I would still recommend to remove this function "setCenter" function.
And with this new code, it's now possible to remove this function at implementation if wanted/needed.

However, as I can't give guaranty that the blur effect is gone, I've added a debounce around the original fix. It allows to keep this fix, and avoid to recenter too frequently during the zoom (avoid the jumping-around effect).

**Review by sbrunner — APPROVED** [review]
Nice thanks :-)

**Comment by maltaesousa** [comment]
Thanks @ger-benjamin for your tests! ping @gnerred

**Comment by ger-benjamin** [comment]
Don't hesitate to open again the issue if needed (but I'm pretty confident on my fix).
You can take the new version of ngeo 2.8, 2.9 and master with the fix in some hours (tomorrow to be sure).

**Comment by gnerred** [comment]
Thanks @ger-benjamin and @maltaesousa , I will test it asap.

**Comment by gnerred** [comment]
I've upgraded our Cartoriviera instance to 2.8.1.170, and the problem is fixed. 

https://map.cartoriviera.ch 

Thanks a lot !

**Pull request merged**
