### PR TITLE
Workaround for error in tooltip config type checking with IE11 

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@fredj, @sbrunner : I did not manage to please typecheck (npm run typecheck).

**Comment by arnaud-morvan** [comment]
Seems I got it with @ts-ignore.
Note that typecheck compare bs.tooltip config to jqueryui.TooltipOption, which is completely different object.

**Comment by fredj** [comment]
try to force the type with:
```js
 body.tooltip(/** @type {Bootstrap.TooltipOption} */ ({
      container: 'body',
      trigger: 'hover',
      selector: '[data-toggle="tooltip"]',

      // Avoid error in config type checking with IE11
      sanitizeFn: $injector.get('$sanitize')
    }));
```

**Comment by arnaud-morvan** [comment]
@fredj: perfect, thanks.

**Pull request merged**
