### PR TITLE
Include required polyfills with Babel

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by ger-benjamin — COMMENTED** [review]
Why do you remove the 3d examples ?

**Comment by sbrunner** [comment]
Good question, It's the only example that have an error with regenerator-runtime event if I add it directly to the example, and this is not used by the UserGroup...

**Comment by ger-benjamin** [comment]
Maybe it would be better to comment them and create a ticket to restore it. That's annoying to trash them... (as long as we don't have a storybook example instead)

**Review by ger-benjamin — APPROVED** [review]
As discussed, let's remove these examples. They are not used anymore and not official supported.
LGTM

**Review by ger-benjamin — APPROVED** [review]

**Review by llienher — APPROVED** [review]

**Pull request merged**
