### PR TITLE
Add "Back" label to mobile navigation

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/camptocamp/ngeo/issues/604

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by pgiraud** [comment]
Can you please add the same for the right menu?

**Comment by pgiraud** [comment]
Is it possible to use the same color as the chevron arrow?

**Comment by tsauerwein** [comment]
Thanks for your feedback, Pierre. I updated my branch, is it ok for you?

**Comment by pgiraud** [comment]
Looks good to me. Please merge.

**Pull request merged**
