### PR TITLE
Fix contextmenu/longpress unlisten

### PR DESCRIPTION
**Pull request by fredj**
#1129 follow-up

### CODE REVIEW

**Comment by fredj** [comment]
otherwise the context menu is active when the draw panel is closed

**Comment by fredj** [comment]
Thanks for any review

**Comment by fredj** [comment]
I will merge soon, last chance to comments ...

**Comment by pgiraud** [comment]
If I understand correctly it's actually the last argument that is of interest. The "scope" one, right?
This looks good to me. Please merge.

**Comment by fredj** [comment]
An event handler must be un-registered with the same arguments as it was registered.
The problem here was that the handler was registered with the `false` and `this` arguments with un-registered without.

**Comment by fredj** [comment]
Thanks for the review !

**Pull request merged**
