### PR TITLE
Can set preload value of Tiles (default to 0)

### PR DESCRIPTION
**Pull request by ger-benjamin**
Improve performance.
(See: https://jira.camptocamp.com/projects/GEO/queues/custom/52/GEO-891)

### CODE REVIEW

**Comment by fredj** [comment]
`preload` option should simply be removed

**Comment by ger-benjamin** [comment]
(done with the Github editor ! )

**Comment by sbrunner** [comment]
I think this this bag :-(, this is to have better performance when we zoom out ...

**Comment by sbrunner** [comment]
In this ticker we don't see anything about preload?
Whant's the deference in therm of loading?

**Comment by ger-benjamin** [comment]
Even on bad internet connection, the change is near invisible on the map, and the tiles around (90% of what you have under your eyes) must be loaded in every cases.

But on the initial load, that a lot of useless tile to load. In the cases of Basel, we load 2.3 Mo of tiled on a total of 4.5Mo (total size of initial load).

If you want, I can (re-)add a configuration value for this parameter. But with fredj  and gberaudo , we though that's useless.

**Comment by sbrunner** [comment]
I just do a test with slow 3g,
An in booth case (tested on github.io 2.2/master) I get all the visible background in about 55s.
and when I zoom out on 2.2 it takes 23s. and on master 13s.
Then in therm of performance we should keep it, and if it's relay wanted we should add an option and the preload should be infinity by default ...

**Comment by ger-benjamin** [comment]
>  I get all the visible background in about 55s.
More like in 55s for master and 51s in 2.2 for me. And in Basel, they load two background in the same time (one for basel, their tiles, and another for the whole switzerland (Swisstopo)). So, that make ~6-8 sec difference. And that's on the startup, so the slower part of our application. Each optimization on this part is interesting for our users.

But **ok**. I'll do a configuration value for that, defined to Infinity by default.

**Pull request merged**
