### PR TITLE
Don't use the example jsdoc tag but indent the code

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by sbrunner** [comment]
Shouldn't we introduce the examples? (with something like «Example: »)

**Comment by sbrunner** [comment]
fix #357

**Comment by sbrunner** [comment]
fix #361

**Comment by sbrunner** [comment]
fix #362

**Comment by fredj** [comment]
@sbrunner I've added the `Example:`

**Comment by sbrunner** [comment]
Excellent, merge if Travis is happy :-)

**Comment by ger-benjamin** [comment]
Sorry, I broke your PR :-/ you should rebase It...

**Comment by fredj** [comment]
@ger-benjamin no problem, it's done

**Pull request merged**
