### PR TITLE
Move gmf.WMSTime to ngeo.WMSTime

### PR DESCRIPTION
**Pull request by adube**
This PR moves the `gmf.WMSTime` service to `ngeo.WMSTime`.

### CODE REVIEW

**Comment by adube** [comment]
Ready for review.

**Comment by fredj** [comment]
unit tests must be adapted

**Comment by adube** [comment]
I'm on it.

**Comment by adube** [comment]
Unit tests moved to ngeo.

**Comment by adube** [comment]
Travis failed, but it seems to be a hiccup.

**Pull request merged**
