### PR TITLE
ObjectEditing - CSS style for tool and icons

### PR DESCRIPTION
**Pull request by adube**
This PR fixes the CSS styling of the ObjectEditing tool, i.e. its tool icons and general appearance.

## To do

 * [ ] The icons are not working in the application, but they do in the example.  This needs to be fixed.
 * [ ] Review

## Live example

First, you need to [log in](https://adube.github.io/ngeo/oe-css-styling/examples/contribs/gmf/authentication.html) using the authentication example.

Then, visit the [ObjectEditing Hub](https://adube.github.io/ngeo/oe-css-styling/examples/contribs/gmf/objecteditinghub.html) example.  Pick the settings you want (make sure to choose the 'hosted' app and not the 'dev' one).

### CODE REVIEW

**Comment by adube** [comment]
@sbrunner I created a live example.  You can see that the **icons** are not working in the application, but they do in the example.  Any hint?

**Comment by adube** [comment]
@sbrunner Do you have any hint regarding the issues with the icons not working in the application?

**Comment by sbrunner** [comment]
I just test it, and I don't succeed to have the icon issue, Can you tel me how to reproduce?

**Comment by adube** [comment]
To test it locally, checkout the branch, then serve, visit the hub example and launch the 'dev' application.

```
git checkout oe-css-styling
make serve
```

then:

 * visit: http://localhost:3000/contribs/gmf/examples/objecteditinghub.html
 * select 'oeedit app. (dev)' in the first drop-down list
 * hit 'Launch Editior'

You will see the icons don't have the correct style.

**Comment by sbrunner** [comment]
Effectively, it's working on Chrome but not on Firefox ...
I think that you should remove the class gmf-icon ...

**Comment by adube** [comment]
You are correct.  I'll fix this.  Thanks.

**Pull request merged**
