### PR TITLE
Layer opacity

### LINKED ISSUE #817: Definir l'opacité "layer interne"
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

### LINKED ISSUE #818: Definir l'opacité "layer externe"
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

### PR DESCRIPTION
**Pull request by olivierSemet**
Closes #818 
Closes #817 

Live example: [here](https://oliviersemet.github.io/ngeo/818-external-layer-opacity/examples/contribs/gmf/apps/desktop/)

@fredj or @pgiraud could you check please?

### CODE REVIEW

**Comment by fredj** [comment]
One minor enhancement could be made; the popover should be closed as soon as the layer group is moved (drag and drop)

Looks very good to me.

**Comment by olivierSemet** [comment]
@fredj I agree. There is an other issue, when you srcoll the layertree, the popover should be destroyed. As discussed with @pgiraud, it will be done in a next PR.

**Comment by fredj** [comment]
> [...] it will be done in a next PR.

ok, can you please create an issue for that?

**Comment by fredj** [comment]
please rebase your branch and it will be good to merge

**Comment by fredj** [comment]
Thanks @olivierSemet

**Pull request merged**
