### PR TITLE
Don't load mainmodule in examples

### PR DESCRIPTION
**Pull request by fredj**
https://jira.camptocamp.com/browse/GSGMF-219

### CODE REVIEW

**Comment by ger-benjamin** [comment]
(I've restarted the build, it was timed out)

**Comment by sbrunner** [comment]
Why?

**Comment by fredj** [comment]
Because we want the examples to load only what they need; not everything from gmf

**Comment by sbrunner** [comment]
This is to have a big part in the commons part and It's also what we want ...

**Pull request merged**
