### PR TITLE
Support HTML in feature attributes (query popup)

### PR DESCRIPTION
**Pull request by tsauerwein**
This PR proposes to use [angular-sanitize](https://docs.angularjs.org/api/ng/directive/ngBindHtml) to sanitize feature attributes so that HTML code is rendered as HTML.

Closes https://github.com/camptocamp/ngeo/issues/965

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by tsauerwein** [comment]
@sbrunner Also ok for you?

**Comment by sbrunner** [comment]
OK from now :-)

**Comment by tsauerwein** [comment]
Thanks for the review.

**Pull request merged**
