### PR TITLE
Rename ngeoModule and gmfModule

### PR DESCRIPTION
**Pull request by fredj**
to be discussed

### CODE REVIEW

**Comment by sbrunner** [comment]
And what about the provide/requires?

**Comment by gberaudo** [comment]
As a second thought, I think it will be more consistent with `goog` not to provide/require the module explicitely. So +1 for @fredj suggestion.

**Comment by fgravin** [comment]
> with goog not to provide/require the module explicitely

What do you mean ?
I don't really see the issue about the module variable.

**Comment by sbrunner** [comment]
Same as @gberaudo :-)

**Comment by gberaudo** [comment]
I mean it is fine to only require the namespace and get the module like this:
```
goog.require('ngeo');
angular.module('myapp', [ngeo.module.name]);
```

**Comment by sbrunner** [comment]
Steal in WIP ?

**Comment by fredj** [comment]
If everyone agrees, this can be merged.

**Comment by fgravin** [comment]
Go ahead thanks

**Pull request merged**
