### PR TITLE
Reduce tiles preload to 1 level

### PR DESCRIPTION
**Pull request by fredj**
GSGMF-1371

### CODE REVIEW

**Comment by sbrunner** [comment]
I don't see a real différance from the previous one...

**Comment by fredj** [comment]
There's less tiles downloaded on initial page load and when navigating

**Review by ger-benjamin — COMMENTED** [review]
I guess #6284 supersedes this PR ? Can we close it ?

**Comment by fredj** [comment]
> I guess #6284 supersedes this PR ? Can we close it ?

yes

**Pull request closed without merging**
