### PR TITLE
Adapt WFS-version for reading of GML2 results

### PR DESCRIPTION
**Pull request by RenataMuellerC2C**
GSGMF-1505

### CODE REVIEW

**Review by llienher — APPROVED** [review]
Looks good to me

**Review by sbrunner — CHANGES_REQUESTED** [review]
For what reason do you do this change?

**Comment by RenataMuellerC2C** [comment]
@sbrunner The reading of the features fails for polygon layers with output format GML2 like landuse_alias, if the version of olFormatWFS is set to the default 1.1.0. Or should we change that on the qgis side?

**Review by sbrunner — APPROVED** [review]
No, that looks good :-)

**Pull request merged**
