### PR TITLE
Filter - Support contextual menu in spatial rule

### PR DESCRIPTION
**Pull request by adube**
This PR adds the contextual menu that is shown on "right click" on a vector feature while editing a spatial rule in the filter tool.

The following items are shown per geometry type:

- circle: move
- line: move, rotate
- polygon: move, rotate
- rectangle: move, rotate

## Todo

 * [x] Wait for #2433 to be merged
 * [ ] review

## Live demo

 * https://adube.github.io/ngeo/filter-geom-contextual/examples/contribs/gmf/apps/desktop_alt/

### CODE REVIEW

**Comment by adube** [comment]
Ready for review.

**Comment by ybolognini** [comment]
Very nice!

3 issues:
 * CSS alignement on Firefox 
CHROME (good)
csschrome
FIREFOX (not good)
cssfirefox
 * When a criteria's popup menu is open, one can still select "Save filter" button, even if the popup is over the button. On the view below, one can click on the right of the popup menu and activate "Save filter" button:
savefilter
 * Follow the steps:
   * Draw a circle for a Spatial filter
   * Do not close popup menu (circle is still editable)
   * Switch to Draw tool
   * Even if the Spatial filter's circle is hidden, it is still editable

**Comment by adube** [comment]
Rebased onto master.  Ready to merge once Travis is done.

**Comment by adube** [comment]
@fredj Travis is happy.

**Pull request merged**
