### PR TITLE
Move the rateLimitWait option from ngeo to gmf

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by gberaudo** [comment]
Why not keep it there?

**Comment by fredj** [comment]
Because this configuration applies to `gmf`, the `ngeo` part must be as generic as possible (no assumption that the remote server can handle this rate)

**Comment by gberaudo** [comment]
OK, I understand now. Please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
