### PR TITLE
Make control directive rely on control.setTarget

### PR DESCRIPTION
**Pull request by elemoine**
This is WIP depending on https://github.com/openlayers/ol3/pull/3139.

### CODE REVIEW

**Comment by elemoine** [comment]
This is now ready for review. With this the control directive relies on a control being made available in the parent scope, as opposed to a function that returned a control.

Please review.

**Comment by pgiraud** [comment]
It makes things simpler. I like it.
This looks good. Please merge.

**Comment by elemoine** [comment]
And the problem was that the function was executed with `window` as its scope, instead of the controller as one would have expected.

**Comment by asaunier** [comment]
I guess this implies changes in projects that use the ngeo-control directive?

**Comment by elemoine** [comment]
> I guess this implies changes in projects that use the ngeo-control directive?

Yes, the user just needs to provide an expression that evaluates to a control (with no target and not already added to the map).

**Pull request merged**
