### PR TITLE
Get the default basemap from the user functionalities

### LINKED ISSUE #964: Set default background layer
Currently we cannot set the default background layer on mobile.

### PR DESCRIPTION
**Pull request by fredj**
Fixes #964
See #654

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good but shouldn't be documented in the directive?

**Comment by sbrunner** [comment]
Can it be on the 2.0 branch?

**Comment by fredj** [comment]
I'm not sure that `gmf.MobileBackgroundlayerselectorController` is the right place to check the default background.

What about choosing the value (in permalink and gmf.User) in the abstract controller and passing the value to the background selector?

**Comment by fredj** [comment]
Ready to be reviewed

**Comment by sbrunner** [comment]
Looks good for me :-)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
