### PR TITLE
Add back gmf.ThemesEventType.CHANGE on themes change

### LINKED ISSUE #1730: Themes list is not updated after logging
This looks like a regression. The list of themes is not updated when the user logs in.

See "gmf.ThemesEventType.LOAD" in https://github.com/camptocamp/ngeo/pull/993/files

It has been removed in https://github.com/camptocamp/ngeo/pull/878/files

### PR DESCRIPTION
**Pull request by fredj**
todo:
 - [ ] reload the background selector on theme change ?
 - [ ] reload the query manager  on theme change ?
 - [ ] reload tree manager on themes change

fixes #1730

### CODE REVIEW

**Comment by adube** [comment]
In the todo, we should also add:

 * clear themes in themes selector on change
 * clear layers in tree manager on themes change

**Comment by fredj** [comment]
@adube the theme selector is already reloaded. I need to check the tree manager

**Comment by adube** [comment]
@fredj Could we talk about this (live) ?

**Comment by adube** [comment]
@fredj I completed all points mentioned here.  This requires review.

See also a live example: https://adube.github.io/ngeo/themes_load_event/examples/contribs/gmf/apps/desktop_alt/

**Comment by fredj** [comment]
fixes #1730

**Comment by fredj** [comment]
There's is one issue: on login, the selected theme is lost

**Comment by fredj** [comment]
> There's is one issue: on login, the selected theme is lost

false alarm, sorry ...

LGTM, thanks @adube !

**Pull request merged**
