### PR TITLE
Export gmf.source.AsitVD

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by elemoine** [comment]
It is not the way we do it in ngeo. Indeed, we want  `gmf.source.AsitVD` to be exported in `gmf.js` (used by the examples on github.io), but we don't want `gmf.source.AsitVD` to be exported in our applications, which are compiled together with ngeo. If you use `@export` then `gmf.source.AsitVD` will unconditionally be exported. This is why we use separate exports files. Makes sense?

**Comment by fredj** [comment]
makes sense.
we need to remove the `@export` annotation elsewhere in ngeo (https://github.com/camptocamp/ngeo/blob/master/src/directives/scaleselector.js#L92, https://github.com/camptocamp/ngeo/blob/master/src/directives/layertree.js#L135, ...) right ?

**Comment by elemoine** [comment]
> makes sense.
> we need to remove the @export annotation elsewhere in ngeo (https://github.com/camptocamp/ngeo/blob/master/src/directives/scaleselector.js#L92, https://github.com/camptocamp/ngeo/blob/master/src/directives/layertree.js#L135, ...) right ?

No. Both controller classes include methods with `@export` (`getScale` for example). Contrary to `ngeo.source.AsitVD` these methods need to be unconditionally exported, because they're used in Angular templates. And for `@export` to work on these methods their constructors must have an `@export` as well. This is [explained](https://github.com/camptocamp/ngeo/blob/master/docs/guidelines.md#use-export-for-controllers) in our guidelines.

**Comment by elemoine** [comment]
Please merge.

**Comment by fredj** [comment]
And thanks for all your explanations

**Comment by elemoine** [comment]
> And thanks for all your explanations

You can now be the one verifying that PRs/patches are correct with respect to exports/externs… :)

**Pull request merged**
