### PR TITLE
Clear login and password after successful login

### PR DESCRIPTION
**Pull request by arnaud-morvan**
And clear password fields after failed attempts.

https://jira.camptocamp.com/browse/GSGMF-1065
Note that after password change, fields are already cleared.

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks that it should be rebased...

**Comment by arnaud-morvan** [comment]
Well spotted, missing an approve now.

**Comment by sbrunner** [comment]
For me that's looks good, @fredj can you have a secound look?

**Comment by arnaud-morvan** [comment]
@sbrunner @fredj : Can we merge this PR, really simple changes.

**Pull request merged**
