### PR TITLE
Use commander instead of nomnom

### PR DESCRIPTION
**Pull request by fredj**
nomnom is not longer available

### CODE REVIEW

**Comment by sbrunner** [comment]
This should also be done?
https://github.com/openlayers/openlayers/blob/6f54f6c1133e0a0bba7099736b0b413b8a7253d2/changelog/v4.0.0.md#removal-of-deprecated-methods

**Comment by sbrunner** [comment]
Here: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/profile/component.js?utf8=%E2%9C%93#L395

**Comment by sbrunner** [comment]
I'm wrong it use the new syntax...

**Comment by sbrunner** [comment]
@fredj is it ok to merge as it?

**Comment by fredj** [comment]
@sbrunner I want to simplify the code by using `forEach(unlistenByKey)` instead of `ol.Observable.unByKey`

**Comment by sbrunner** [comment]
OK, lets do it :-)

**Comment by fredj** [comment]
I'm on it

**Comment by fredj** [comment]
thanks @sbrunner

**Comment by sbrunner** [comment]
thanks @fredj  :-)

**Pull request merged**
