### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by rbovard**

### CODE REVIEW

**Comment by fredj** [comment]
good catch, thanks !

**Comment by sbrunner** [comment]
Should be rebase on the 2.1 branch :-)

**Comment by rbovard** [comment]
How to do that?

**Comment by sbrunner** [comment]
```
git rebase --interactive origin/2.1
```
removes all lines starting with `pick ` expect yours one :-)

**Comment by rbovard** [comment]
Thanks, done.

**Comment by sbrunner** [comment]
Thanks @rbovard  :-)

**Pull request merged**
