### PR TITLE
Gmf display queries

### PR DESCRIPTION
**Pull request by ger-benjamin**
Strange issue (reason of the [wip] tag on this PR): 
- The dropdown is empty on smartphone (at least on IOS)... (see #663)
- I must add a ng-swipe-left/right to do actions (but I can't test that because of the first point)

Link to, and current state of work, on: camptocamp/c2cgeoportal#1800

~~Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/mobilequery.html (try it on "edit" theme layers)~~

### CODE REVIEW

**Comment by ger-benjamin** [comment]
Can someone review this or at least answer my questions ?
And what can I do with coveralls ? :rabbit:

**Comment by fgravin** [comment]
Ok very good work thanks.
Please rebase then merge.

Is this specific mobile or not ? If yes, add mobile in the name of your files, directives and controllers, thanks.

**Comment by ger-benjamin** [comment]
Despite of these points:

> The dropdown is empty on smartphone (at least on IOS)... (see #663)
> I must add a ng-swipe-left/right to do actions (but I can't test that because of the first point)

I can merge ? I do them in another PR ?

**Comment by fgravin** [comment]
Yes please merge.
Can you do the integration in the mobile app as well ?

**Comment by ger-benjamin** [comment]
Yes also in another PR (that's will be simple but I think we should resolve #663 before)

**Pull request merged**
