### PR TITLE
Disclaimer in a modal

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix: #1989 

Example: https://ger-benjamin.github.io/ngeo/modal-position/examples/contribs/gmf/apps/desktop_alt/

### CODE REVIEW

**Comment by sbrunner** [comment]
@ger-benjamin can you post the status of this pull request this evening :-), thanks ;-)

**Comment by ger-benjamin** [comment]
Yep, In 5 minutes...

**Comment by sbrunner** [comment]
Thanks @ger-benjamin

**Comment by ger-benjamin** [comment]
@sbrunner Please merge if all is right.

**Pull request merged**
