### PR TITLE
Make sure buttons are centered horizontally on iOS

### PR DESCRIPTION
**Pull request by tsauerwein**
Demo: https://tsauerwein.github.io/ngeo/ios-center-button/examples/contribs/gmf/apps/mobile/index.html

Closes https://github.com/camptocamp/ngeo/issues/712

### CODE REVIEW

**Comment by sbrunner** [comment]
Isn't it an issue of the reset.css?
Should the button be added in this block?
https://github.com/shannonmoeller/reset-css/blob/master/reset.css#L6-L18

**Comment by sbrunner** [comment]
More investigation:
* normalise.css don't reset it: https://github.com/necolas/normalize.css/blob/master/normalize.css
* yui2 do it: https://github.com/yui/yui2/blob/master/sandbox/reset/reset.css

...

**Comment by tsauerwein** [comment]
I wouldn't set it for all buttons. For buttons in forms you probably want to keep the default browser-specific style.

**Comment by sbrunner** [comment]
OK, then that's looks good for me :-)

**Comment by fredj** [comment]
+1, travis fail because of #848

**Comment by tsauerwein** [comment]
Thanks for the info, Fred!

I will merge when Travis passes.

**Pull request merged**
