### PR TITLE
Report code coverage

### PR DESCRIPTION
**Pull request by tsauerwein**
When running the tests with `make test` you will now get a coverage statistics:

    $ make test
    #./node_modules/karma/bin/karma start karma-conf.js --single-run
    INFO [karma]: Karma v0.12.16 server started at http://localhost:9876/
    INFO [launcher]: Starting browser PhantomJS
    INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket YcIt3Mba-JVqLKwmZuW3 with id 8708031
    PhantomJS 1.9.8 (Linux): Executed 95 of 95 SUCCESS (0.207 secs / 0.195 secs)

    =============================== Coverage summary ===============================
    Statements   : 40.55% ( 1238/3053 )
    Branches     : 28.65% ( 220/768 )
    Functions    : 34.59% ( 165/477 )
    Lines        : 40.58% ( 1238/3051 )
    ================================================================================
    Full coverage report in: .build/coverage/lcov-report

When running on Travis, the coverage report is also uploaded to coveralls.io. The reports looks like this: https://coveralls.io/builds/4812091

Closes https://github.com/camptocamp/ngeo/issues/494

### CODE REVIEW

**Comment by tsauerwein** [comment]
We could also add a shiny badge to the readme, but right now the coverage is nothing to be proud of... ;)

**Comment by sbrunner** [comment]
In the "Coverage summary" do you know what's the "Statements" and "Branches"?

**Comment by sbrunner** [comment]
Just one question, also that's looks good for me :-)

**Comment by tsauerwein** [comment]
> In the "Coverage summary" do you know what's the "Statements" and "Branches"?

Statements are, well, statements, branches are the branches of if/else conditions. See also: https://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria

Thanks for the review.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Pull request merged**
