### PR TITLE
Introduce the query panel component

### PR DESCRIPTION
**Pull request by adube**
## GSGMF 1047 - phase 3

This patch is the third step towards implementing a new way to query the map by drawing polygons.

This patch introduces a new `<ngeo-query-panel>` component that is bound to the `QueryModeSelector` service and allows to change query query mode and action.

The panel is added:

 * in the ngeo query example
 * in both desktop and desktop_alt applications

## SVG icons

The SVG icons used in the query panel component were copied from those that are in `contribs/gmf/src/icons` into `src/icons`.

## Icon in the apps

The icon in the apps (in the right toolbar) is currently `fa-info`.  I didn't find the icon that looks like a slighly rotated square with round vertice.

### CODE REVIEW

**Comment by adube** [comment]
@fredj Ready for review.

@sbrunner What is the font-awesome name for this icon?

Query_selection_panel_fa

**Comment by adube** [comment]
@sbrunner Any idea how to fix this issue?

```
src/query/panelComponent.js(22,15): error TS2307: Cannot find module './panelComponent.html'.
3088The command "! (npm run typecheck|grep -v '^node_modules/'|grep '^[a-z]')" exited with 1
```

**Comment by adube** [comment]
> @sbrunner Any idea how to fix this issue?
> 
> ```
> src/query/panelComponent.js(22,15): error TS2307: Cannot find module './panelComponent.html'.
> 3088The command "! (npm run typecheck|grep -v '^node_modules/'|grep '^[a-z]')" exited with 1
> ```

I think I got it...

**Comment by adube** [comment]
@fredj Travis is often complaining about things unrelated to the commits I make.  When that happens, I do: `git commit --amend` and hope for the best.

Is there a quicker way to do that?

**Comment by adube** [comment]
@fredj Travis passes!  Ready for review.

**Comment by adube** [comment]
Okay, I'm loosing patience with Travis.  Would someone please help me figure out why it is always failing now?  It was fine yesterday.

**Comment by sbrunner** [comment]
I think that your pull request should be rebsed ...

**Comment by adube** [comment]
Rebased.

**Comment by adube** [comment]
@fredj Ready for review.

**Comment by adube** [comment]
Thanks for the review.

**Pull request merged**
