### PR TITLE
Reorganise less files

### LINKED ISSUE #439: Rework on the mobile.less
In contrib/gmf/apps/mobile/less/mobile.less we should have something like:
```less
@import '../../../less/mobile-base.less';
@import '../../../less/search.less';
```
we should move:
`nav.less` -> `mobile-nav.less`

and we should create:
`base.less` with:
```less
@import (inline) '../../../node_modules/openlayers/css/ol.css';
@import (inline) '../css/reset.css';
@import '../../../node_modules/bootstrap/less/bootstrap.less';

@import 'vars.less';

body {
  overflow: hidden;
}

a {
  text-decoration: none;
}
```
`mobile-base.less` with:
```less
@import 'base.less';
@import 'map.less';
@import 'mobile-nav.less';
```

### PR DESCRIPTION
**Pull request by sbrunner**
fix #439

### CODE REVIEW

**Comment by fredj** [comment]
+1

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by fredj** [comment]
http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html is broken

**Comment by sbrunner** [comment]
Thanks @fredj I will have a look :-)

**Pull request merged**
