### PR TITLE
Fix permalink for add single layer and add theme

### PR DESCRIPTION
**Pull request by RenataMuellerC2C**
GSGMF-1528

### CODE REVIEW

**Comment by ger-benjamin** [comment]
For which ticket it is ?

**Comment by ger-benjamin** [comment]
Your changes looks good but it's not what I've expected to fix permalink issues. I'll take a longer time to review.
Plus, I've a similar (but not equal) problem with the permalink in GSGMF-1527. I would like to take tie to see if it's related.
Please, do not merge too fast this PR.

**Comment by ger-benjamin** [comment]
@RenataMuellerC2C Your fix looks not working with my own test. How do you have tried your own solution ?

My fix, for my own problem, looks also fix yours #7064 Could you try ?

**Comment by RenataMuellerC2C** [comment]
@ger-benjamin Yes your fix also solves my test cases:
clean layertree
1. add 'Paysage', deactivate 'tourisme' and activate 'accomodation', add bus-stop by search.
2. add 'Culture', activate only the 'bank', add theme 'watermanagement'.
So this PR will not be needed any more.

**Comment by ger-benjamin** [comment]
Superseded by #7064

**Pull request closed without merging**
