### PR TITLE
Coding style fixes

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by ger-benjamin** [comment]
With a git grep goog.isArray`, I got that:

````
src/directives/sortable.js:          goog.asserts.assert(goog.isArray(sortable));
src/ol-ext/format/featurehash.js:    goog.asserts.assert(goog.isArray(fillColor), 'only supporting fill colors');
src/ol-ext/format/featurehash.js:        styles = goog.isArray(styles) ? styles : [styles];
src/services/getbrowserlanguage.js:        if (!goog.isArray(browserLanguages)) {
src/services/print.js:    var styles = (styleData !== null && !goog.isArray(styleData)) ?
src/services/print.js:    goog.asserts.assert(goog.isArray(styles));
src/services/print.js:  goog.asserts.assert(goog.isArray(fillColor), 'only supporting fill colors');
src/services/print.js:          goog.isArray(fillColor), 'only supporting fill colors');
````

**Comment by fredj** [comment]
@ger-benjamin are you sure you're on the master branch ?
See #1075

**Comment by ger-benjamin** [comment]
@fredj Oups, nop, forget my comment. I'was probably on another branch when I mad my git grep. I got nothing more now.

**Comment by ger-benjamin** [comment]
Please merge

**Comment by fredj** [comment]
Thanks for the review

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
