### PR TITLE
Document gmflayertree openlinkinnewwindow attribute

### LINKED ISSUE #2970: layertree's openLinksInNewWindowFn not documented
attribute openLinksInNewWindowFn in gmflayertree must be documented

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix #2970
Must be reported in branch 2.2 and master

### CODE REVIEW

**Comment by fredj** [comment]
@ger-benjamin the travis check keeps failing but doesn't seems related to you changes

**Comment by ger-benjamin** [comment]
@fredj what can I do ?

**Comment by sbrunner** [comment]
The tests errors speaks about openLinksInNewWindowFn ...

**Comment by ger-benjamin** [comment]
I've not seen that. Thanks I'll correct that

**Comment by sbrunner** [comment]
:-)

**Comment by ger-benjamin** [comment]
Done

**Comment by fredj** [comment]
all good, please merge

**Pull request merged**
