### PR TITLE
`make gh-pages` is broken.

### PR DESCRIPTION
**Pull request by fredj**
by #385

### CODE REVIEW

**Comment by sbrunner** [comment]
Where do you see that's broken ?

**Comment by fredj** [comment]
With a `make clean gh-pages`

**Comment by fredj** [comment]
Error was:
```
mkdir -p .build/examples-hosted/
.build/python-venv/bin/python buildtools/generate-examples-index.py buildtools/examples-index.mako.html examples/geolocation.html examples/interactionbtngroup.html examples/animation.html examples/search.html examples/permalink.html examples/mapfishprint.html examples/backgroundlayerdropdown.html examples/simple.html examples/interactiontoggle.html examples/profile.html examples/layervisibility.html examples/layertree.html examples/measure.html examples/backgroundlayer.html examples/layeropacity.html examples/importfeatures.html examples/control.html examples/modal.html examples/scaleselector.html examples/layerorder.html > .build/examples-hosted/index.html
mkdir -p .build/examples-hosted/contribs/gmf/
.build/python-venv/bin/python buildtools/generate-examples-index.py buildtools/examples-index.mako.html contribs/gmf/examples/search.html contribs/gmf/examples/locationchooser.html contribs/gmf/examples/simple.html contribs/gmf/examples/asitvd.html > .build/examples-hosted/contribs/gmf/index.html
make: *** No rule to make target `contribs/gmf/apps/mobile/build', needed by `.build/examples-hosted/contribs/gmf/apps/mobile'.  Stop.

```

**Comment by sbrunner** [comment]
OK, looks good, merge when Travis is happy :-)

**Comment by fgravin** [comment]
Yes i misunderstood the workflow.
I thought we needed a `make check` before doing the `make gh-pages`.

So, does the `gh-pages` builds examples before publishing them ?

**Comment by sbrunner** [comment]
Yes, if we use make correctly a command should always do anything to be done :-)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
