### PR TITLE
Don't add a vertex on right click

### LINKED ISSUE #1085: gmf-drawfeature - actions menu - don't add vertex
When a feature is already selected, the modify interaction is activated. This means that a vertex can be added on any segment.
A vertex is added even when the user only wants to display the actions menu.

### PR DESCRIPTION
**Pull request by fredj**
Fixes #1085 

work in progress

### CODE REVIEW

**Comment by sbrunner** [comment]
Is it ready?

**Comment by fredj** [comment]
It's works but not on touch devices

**Comment by fredj** [comment]
After discussion with @ybolognini this PR will be merged and improved later

**Comment by tsauerwein** [comment]
@fredj, could it be that you pushed forced to your ol3 branch? Because the commit referenced in the ngeo package.json does no longer work (`fredj/ol3#afb2084`).

**Comment by tsauerwein** [comment]
Besides this change in ol3 makes the build fail:
https://github.com/openlayers/ol3/commit/8c8c4c3df4b4f8bb6c4aefe55aeb7989b3967289#diff-8494393ae9d5dabf08260f09d9403203L3

```
node buildtools/build.js .build/ngeo.json dist/ngeo.js
info ol Parsing dependencies
ERR! Unsatisfied dependency "ol.style.StyleFunction" in script: /home/tsauerwein/projects/ngeo/src/services/featureoverlay.js 
make: *** [dist/ngeo.
```

**Comment by sbrunner** [comment]
see #1184

**Pull request merged**
