### PR TITLE
The legend is now a boolean

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by fredj** [comment]
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/data/themes.json needs to be updated

**Comment by sbrunner** [comment]
Why do we have a copy?

**Comment by fredj** [comment]
the files is used by the examples in contribs/gmf/examples/

**Comment by sbrunner** [comment]
Why thy don't use the service directly, or is it created at the build time?

**Pull request merged**
