### PR TITLE
Use the good GetMap url from the GetCapabilities

### PR DESCRIPTION
**Pull request by oterral**
The good WMS url to use is written in the Capabilities section not in Service

WMS links to test:

https://geoweb.so.ch/wms/isboden?SERVICE=WMS&REQUEST=GetCapabilities
http://services.sentinel-hub.com/v1/wms/570197e0-4b40-4783-b261-30a054d715bb

### CODE REVIEW

**Comment by oterral** [comment]
any opinions?

**Comment by ponceta** [comment]
http://www.sigip.ch/main/wsgi/mapserv_proxy

Other possible wms link to test. (GMF base WMS url)

**Comment by gberaudo** [comment]
@sbrunner, do you have opinion on this?

**Comment by sbrunner** [comment]
Actually I don't have any opinion about it, it's seem better like it but we will have probably an other opinion the day we have an issue with a server who has not the same URL :-(

**Comment by oterral** [comment]
According to the spec the good url is in the Capability tag.

**Comment by sbrunner** [comment]
Yes be we also use it to do GetFeature Info, than id the URLs are defendant we should store all of them. For me we can merge it and when we had an issue about that, we will store all of them ...

**Comment by gberaudo** [comment]
OK,then I am merging it, thanks all.

**Pull request merged**
