### PR TITLE
Remove SVG build-time modifications

### PR DESCRIPTION
**Pull request by sbrunner**
See JIRA issue: [GSNGEO-12](https://jira.camptocamp.com/browse/GSNGEO-12).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9448/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9448/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9448/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9448/merge/apidoc/)

[GSNGEO-12]: https://camptocamp.atlassian.net/browse/GSNGEO-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ger-benjamin** [comment]
The goal is full filled, but the result is a bit ugly. 
Do you have envisaged to load svg icon/images via css ?

**Comment by sbrunner** [comment]
> Do you have envisaged to load svg icon/images via css?
This kind of configuration is so difficult to make it wheel working, then no...

**Comment by sbrunner** [comment]
An alternative can be to make JS file per icon, and include them in the template, then they are in JS also!

**Comment by sbrunner** [comment]
=> Moved in #9454

**Pull request closed without merging**
