### PR TITLE
Add remove group button in layertree

### LINKED ISSUE #821: Remove Layer group block
Related to: https://github.com/camptocamp/c2cgeoportal/issues/1708

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fgravin** [comment]
Could you please provide a test url.
Also, did you have spec for this feature ? @pgiraud is working on layertree mockups.
Thanks

**Comment by fredj** [comment]
I've only found this screenshot: https://github.com/camptocamp/ngeo/issues/821#issuecomment-192192512

**Comment by sbrunner** [comment]
Thanks for the tests :-)

**Comment by fredj** [comment]
See https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop#extra-actions for the spec

**Comment by fredj** [comment]
I will merge this PR as it and @olivierSemet will rework the UI later

**Comment by fredj** [comment]
Note: UI stuff removed

**Pull request merged**
